config/deploy.rb

attempted to deploy to the test environment just now, and was snagged by the two things fixed here.  deployment worked after these changes were made.

fix cap and ruby versions to unbreak deployment

---

config/deploy.rb

this fixes a deployment error in environments which don't have SSH key auth setup for github

switch to https version of :repo_url, now that repo is public

---

lib/pre_assembly/bundle.rb
lib/pre_assembly/digital_object.rb
lib/pre_assembly/project/salt.rb
spec/bundle_spec.rb
spec/digital_object_spec.rb

This makes it clear(er) that preassembly can pass through non-publish attributes (like the new `role` attribute, see https://github.com/sul-dlss/dor-services/pull/338).

Replace publish_attr configuration with file_attr

---

README.rdoc
bin/remediate

This can be useful for large remediation jobs that are a low priority, which allows them to run at a slower pace and thus generating less concurrent load on the system while other higher priority jobs are running concurrently.

allow a pause time to be set in remediation scripts

---

README.md
spec/spec_helper.rb

README was telling us to cp a non existent file
set ROBOT_ENV to test, so tests are not trying to run in dev

README out of date and sent spec environment

---

lib/pre_assembly/digital_object.rb
spec/digital_object_spec.rb
spec/object_file_spec.rb
spec/remediate_spec.rb
spec/revs_project_specific_spec.rb
spec/smpl_project_specific_spec.rb

The accessors were already declared... then not used.
Note the economy of just using a getting method for `dor_object` rather than a special method to get the object and set `@dor_object`.
There was no benefit to enumerating a bunch of symbols, then iterating through them in a loop declaring `attr_accessor` for each vs. just calling `attr_accessor` once with the same symbols.

Use attributes

---

config/projects/TEMPLATE.yaml
lib/pre_assembly/bundle.rb
spec/bundle_spec.rb

Added one additional accessor where an instance_var didn't have one.
Use `||=` and `&&=` instead of explicit `if obj.nil?` checks.
Note the conflict between declared attributes and some methods in the
namespace that override getters but do not behave like getters.
Removed GC and Profiler code.

Use attributes in Bundle

---

bin/mods_report
bin/mods_report2
config/boot.rb
config/environments/production.rb
devel/mjf_transform.rb
devel/revs_get_druid_from_sourceid.rb
devel/revs_update_images.rb
devel/revs_update_metadata.rb
lib/pre_assembly/bundle.rb
lib/pre_assembly/digital_object.rb
lib/pre_assembly/remediation/remediate.rb
lib/pre_assembly/smpl_precontent_metadata.rb

After this PR, `rubocop --only=Layout` runs cleanly.
Changes with more substantive (manual) refactoring are in their own commits.

Layout and cleanup fixes

---

.travis.yml

This is already provided by default:
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

Remove now-redundant RAILS_ENV=test in travis setup

---

config/boot.rb

Effectively, boot was assigning RAILS_ENV, which is counterproductive.  Having a default value is fine, but otherwise allow `Rails.env` to take its own default.

Do not double-assign RAILS_ENV

---

config/deploy.rb
config/deploy/old_prod.rb
config/deploy/old_stage.rb
config/deploy/prod.rb
config/deploy/stage.rb

Effectively, this treats the "old" sets as the exception rather than the rule.  Note: deploying master to `lyberservices` will break things.  Use the `v3-legacy` branch for that.
Remove ignored/redundant rvm lines (we have `.ruby-version` file).
Use ssh to access github.

Baseline deploy.rb should suit new systems, not lyberservices

---

lib/pre_assembly/bundle.rb

This will free up other code to do less variable-assignment caching.

Add caching to #objects_to_process

---

.gitignore
config/cli_environments/development.rb

This allows `bundle exec rails console` to succeed on a local system.

Add a dummy dev config

---

config/cli_environments/development.rb
config/cli_environments/test.rb

this was working for me when i pulled the branch used in #130, but then it wasn't w/o the modifications mentioned once it got merged to master.  🤷‍♂️ 
but works again with this change.

need to explicitly require dor-services in cli_environment configs for rails console to work

---

README.md
app/lib/pre_assembly/bundle.rb
app/lib/pre_assembly/digital_object.rb
app/lib/pre_assembly/reporting.rb
config/projects/TEMPLATE.yaml
config/projects/reg_example.yaml
spec/lib/pre_assembly/bundle_spec.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/test_data/project_config_files/folder_manifest.yaml
spec/test_data/project_config_files/local_dev_folder_manifest_noreg.yaml
spec/test_data/project_config_files/local_dev_gould.yaml
spec/test_data/project_config_files/local_dev_reid_dennis.yaml
spec/test_data/project_config_files/local_dev_sohp.yaml
spec/test_data/project_config_files/local_dev_sohp_discovery_manifest.yaml
spec/test_data/project_config_files/local_dev_sohp_via_symlink.yaml
spec/test_data/project_config_files/proj_revs.yaml
spec/test_data/project_config_files/proj_revs_bad_manifest.yaml
spec/test_data/project_config_files/proj_revs_no_cm.yaml
spec/test_data/project_config_files/proj_revs_old_druid.yaml
spec/test_data/project_config_files/proj_rumsey.yaml
spec/test_data/project_config_files/proj_sohp2.yaml
spec/test_data/project_config_files/proj_sohp3.yaml
spec/test_data/project_config_files/proj_sohp4.yaml
spec/test_data/project_config_files/sohp_files_and_folders.yaml
spec/test_data/project_config_files/sohp_files_only.yaml

The following options are removed because their values can be assumed:
- `cleanup: false`
- `compute_checksum: true`
- `new_druid_tree_format: true`
- `init_assembly_wf: true`
- `limit_n` (no limit)
- `reaccession: false`
- `resume: true`
- `show_progress: false` (irrelevant)
- `throttle_time: 0`
- `uniqify_source_ids: false`
- `validate_usage: true`
Update YAML fixtures.  Resolve setup failure of one test object.
Only PART of #133, which is amazing given that so much logic is already removed here, especially many "developer only" features.

Removing scope: unused options and logic

---

Gemfile
config/deploy.rb

Connects to #98  (which I didn't realize until I wasted time on it ...)
I tried to fix it, but gave up.  Hopefully there is enough context now to help the next person.  I worry this will bite us when we try to actually execute code ... but we'll cross that bridge later.
Here's what I put in the code:
```ruby
#
#
```

add more context to honeybadger notification problem

---

app/lib/pre_assembly/bundle.rb

This is an instance of the problem described in a FIXME earlier in the file, namely using the same name for a method and an attribute.

validate_files one-character fix

---

app/lib/pre_assembly/bundle.rb

to prevent the delegation of that method from clashing with Bundle#validate_files
follow on to #188

make a BundleContext.validate_files? method

---

app/lib/pre_assembly/bundle.rb
app/lib/pre_assembly/digital_object.rb
config/initializers/dor_services.rb
config/initializers/dor_workflow_service.rb
config/settings.yml
spec/lib/pre_assembly/bundle_spec.rb
spec/support/bundle_setup.rb
spec/test_data/project_config_files/smoke_test.yaml

Makes bundle.run_pre_assembly runnable from the console and adds a smoke test sort of spec for that.
Also comments out the currently unused config stuff to talk to workflow services -- we are currently set up to go via dor services url.  Ticket #194 is for converting us to use dor-workflow-services gem for this instead.
Note that given the development and test configurations, I am certain that the only external thing we need in this rails app for `run_pre_assembly` is the url to the dor workflow service.
Closes #165 
Closes #181

Pa console runnable

---

app/lib/bundle_context_temporary.rb
app/lib/pre_assembly/bundle.rb
app/models/bundle_context.rb
app/models/user.rb
db/migrate/20180905214414_create_bundle_contexts.rb
db/schema.rb
spec/lib/bundle_context_temporary_spec.rb
spec/lib/pre_assembly/bundle_spec.rb
spec/models/bundle_context_spec.rb
spec/models/user_spec.rb
spec/support/bundle_setup.rb

In the `db/migration` these are the following attributes I used and why:
form website: https://sul-preassembly-stage.stanford.edu/bundle_context
`project_name` as a `string` => instead of just `project` on the website (thought adding name might be more clear.)
`content_structure` as an `integer` => this used to be `project_style`. In the code `project_style` is a hash of hashes that contains `content_structure` and `get_druid_from`. `Get_druid_from` is going to be hard coded, and so I thought we could use `content_structure` as the name here instead of `project_style`. This will be easier to use it as an enum. So it isn't like this: 
```
{
:project_style => {
:content_structure => [:simple_image, :simple_book, :book_as_image, :book_with_pdf, :file, :smpl]
}
}
```
but instead:
```
{ …
```

BundleContext Active Record Model

---

config/initializers/resque.rb
config/resque-pool.yml
config/resque.yml
lib/tasks/resque.rake

`resque-pool` now runs. This PR is non-conflicty.
Closes #208

Resque/pool config, initialization and tasks

---

app/models/bundle_context.rb
config/projects/TEMPLATE.yaml
spec/models/bundle_context_spec.rb

When method by method and moved over methods in BundleContextTemp to
BundleContext AR model. Included validations as well has methods that
are used throughou the application.
Wrote RSpect tests for the methods moved over, and left ticket numbers
on outstanding work.
closes #176 
closes #182

bundle_context class to bundle_context AR Model

---

app/lib/bundle_context_temporary.rb
app/lib/csv_importer.rb
app/lib/pre_assembly/bundle.rb
app/lib/pre_assembly/smpl.rb
app/models/bundle_context.rb
spec/lib/bundle_context_temporary_spec.rb
spec/lib/csv_importer_spec.rb
spec/lib/pre_assembly/bundle_spec.rb
spec/models/bundle_context_spec.rb

* centralize this shared functionality to a file in app/lib, move tests to corresponding spec file, have everything that needs the functionality use the app/lib method
* give it a slighty better name
* stop delegating unnecessarily in Bundle, and stop calling it via Bundle.  remove duplicate test in bundle_spec.rb
* excise unnecessary redefinition and tests in bundle_context_temporary and its _spec
* switch to using the more standard ArgumentError instead of the custom BundleUsageError

clean up the csv import functionality

---

app/models/bundle_context.rb
app/models/job_run.rb
db/migrate/20180910225753_create_job_runs.rb
db/schema.rb
spec/models/job_run_spec.rb

Creates a single ActiveRecord model `JobRun` that will be created when the ActiveJob is run with the a `BundleContext` instance, when the ActiveJob is completed, the `output_location` where either the Discovery Report or the Pre Assembly results are stored on the file system. 
This commit also removes the `DiscoveryReportRun` and `JobAssemblyRun` classes in favor of the single class `JobRun` that now has a `job_type` enum for the type of report.
Closes #175

Job history active record

---

spec/models/job_run_spec.rb

spawned by a nitpick on #239: https://github.com/sul-dlss/pre-assembly/pull/239/files#r216867660

make the output_location in the discovery_report_run test fixture more realistic

---

app/services/discovery_report.rb
app/views/discovery_report/_row.text.erb
app/views/discovery_report/show.text.erb
spec/services/discover_report_spec.rb
spec/views/discovery_report/show.text.erb_spec.rb

These are stub templates, but show structure and test it.  I don't mind if reviewers prefer to wait for them to be further fleshed out, but they are mergeable as is.  Since there is some confusion about how these components might work together, this may be clarifying.
Note: because of the Enumerator, we can use the form:
```ruby
render partial: 'row', collection: @discovery_report.each_row
```
That knows to iterate over the Enumerator.
We can also imagine other template outputs (JSON, HTML, etc.) based on the same structure.

DiscoveryReport templates

---

app/lib/pre_assembly/reporting_old.rb
config/deploy.rb
config/initializers/dor_services.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml

The impetus for this PR is #78 -- have job outputs in an appropriate location.   This should be a configuration setting, and has nothing to do with dor-services.
It seemed a propitious time address #169 to move config data into config/settings/#{RAILS_ENV}.yml file and having the dor_services initializer turn the settings into ruby code.
Connects to #169 which will be complete when config/cli_environments is removed from shared_configs and from preassembly code base.
Connects to #78 which will use the `job_output_parent_dir` setting.
Note that the edit to reporting_old class helped me test this on the console on -stage;  I know the class is going away.

use yml settings and dor_services initializer for configuration

---

app/models/job_run.rb
db/migrate/20180914014133_job_run_job_type_not_null.rb
db/schema.rb
spec/models/job_run_spec.rb

Closes #252:
> -  add a migration that puts a NOT NULL constraint on the job_runs.job_type column.
> -  add a validation to the JobRun class that always expects the presence of job_type.

JobRun#job_type is required and it's preassembly without a hyphen

---

app/controllers/bundle_context_controller.rb
app/views/bundle_context/_yaml_form.erb
spec/controllers/bundle_context_controller_spec.rb
spec/views/bundle_context_spec.rb

The controller and view now validates using the `BundleContext` model and will display error messages using Bootstrap 4. 
User authentication and conditional logic for running `PreassemblyJob` and `DiscoveryReportJob` in controller are still outstanding and need tickets.
Closes #137
Closes #140

Added BundleContext validation and tests in controller and erb

---

app/controllers/bundle_context_controller.rb
spec/controllers/bundle_context_controller_spec.rb

No need to separately `find_by` when rspec gives us the `assigns` method.  It gives the tests access to the **same** object the template would receive (even better than a different object -- or `nil` -- returned by `find_by`).
Uses devise helper `sign_in` method and removes hardcoded `User.create` in controller (meaning only one object could ever be created, since the subsequent `User.create` would certainly fail).
Controller is not concerned with Job directly, only with creating a `JobRun` object.
`current_user` is one of the `bundle_context_params`, logically.  Pass it to `.create`.
`bundle_input_b` doesn't exist anymore, and the model still requires the `bundle_dir` to exist to be valid (and saved). Changed it to `smpl_multimedia`.
This fixes the build.

Tweak BundleContextController and rework tests

---

app/lib/pre_assembly/bundle.rb

The strangest thing is that we don't seem to actually declare anywhere the novel error class we were using.
Build is broken without #289, but this can be merged afterwards.
Fixes #204

Replace BundleUsageError w/ RuntimeError

---

app/jobs/discovery_report_job.rb
app/jobs/preassembly_job.rb
app/models/bundle_context.rb
app/models/job_run.rb
spec/models/bundle_context_spec.rb
spec/models/job_run_spec.rb

Wires in `JobRun` as param to both jobs and auto-`enqueue!`s objects via `after_create` hook.
Cleanups:
- Not everything is about validation, so don't nest under it in spec
- Don't need to confirm how enums work after identifying the values: that's rails internals
- `require 'rails_helper'` is handled by `.rspec`
- consolidate the presence validations in BC.
Part of #85 
closes #267

Job wire up

---

app/controllers/bundle_contexts_controller.rb
app/models/bundle_context.rb
db/schema.rb
spec/controllers/bundle_contexts_controller_spec.rb
spec/models/bundle_context_spec.rb

This is code to get an appropriate output_dir for a BundleContext object, so discovery_report and preassembly_job can put their file artifacts in an appropriate location.  This PR also ensures the output directory is created as appropriate.  (Note that ticket #310 was created for the app to do more than give the rails error page and leave admins to spelunk through logs)
Missing:  actually giving specific filenames for said output, except the progress.yml output file.   This is the remaining checkbox in #78.
There are 3 small refactor commits first, and one at the end -- I can move them to a separate PR if desired.
Connects to #78

Job output parent dir

---

spec/controllers/bundle_contexts_controller_spec.rb
spec/models/bundle_context_spec.rb
spec/models/job_run_spec.rb
spec/models/user_spec.rb
spec/support/bundle_setup.rb

RSpec tests use only the username, need to fix to use the email

The user.sunet_id is saved w/ the email not the username

---

app/models/bundle_context.rb
spec/controllers/bundle_contexts_controller_spec.rb
spec/models/bundle_context_spec.rb
spec/models/job_run_spec.rb

Per instructions from Ben on Slack, captured in #78 comments, use the project name rather than the bundle dir in the output directory for a bundle context.
Also, per separate slack conversation, also captured in #78 comments, restrict the characters allowed for the project name.
Lastly, fixes broken travis build.
Connects to #78

bundle_context: project_name alphanum-ish only; output_dir uses project_name instead of bundle_dir

---

Gemfile
Gemfile.lock
app/assets/javascripts/job_runs.js
app/assets/stylesheets/job_runs.css
app/controllers/job_runs_controller.rb
app/models/bundle_context.rb
app/models/user.rb
app/views/job_runs/show.html.erb
config/routes.rb
spec/controllers/bundle_contexts_controller_spec.rb
spec/controllers/job_runs_controller_spec.rb
spec/factories/users.rb
spec/mailers/job_mailer_spec.rb
spec/models/bundle_context_spec.rb
spec/models/job_run_spec.rb
spec/models/user_spec.rb
spec/rails_helper.rb
spec/support/bundle_setup.rb
spec/views/job_runs/show.html.erb_spec.rb

Started with `rails generate controller JobRuns show`.
With modifications for `JobRun.find` and devise integration in spec.
Introduced FactoryBot and added a factory for users, converting specs over to use the factory where applicable.  I propose merging this as is to enable @jermnelson to work more on the `JobRunsController` UI.  Meanwhile, I will work on adding the other factories (ultimately to include one for `JobRun`).  
One TODO that would make sense (and we currently don't have) is a `:show` template partial for a `BundleContext`.  If we had one, I would probably try to reuse it in the `JobRun` show template (at least, when the job has not yet completed).  Most of the "input" the user cares about is in the BC object, so it makes sense to display that alongside (or immediately …

JobRunsController

---

app/models/bundle_context.rb
spec/controllers/bundle_contexts_controller_spec.rb
spec/lib/pre_assembly/bundle_spec.rb
spec/models/bundle_context_spec.rb
spec/support/bundle_setup.rb
spec/test_data/project_config_files/flat_dir_images.yaml
spec/test_data/project_config_files/images_jp2_tif.yaml
spec/test_data/project_config_files/obj_dirs_images.yaml
spec/test_data/project_config_files/smpl_multimedia.yaml

in addition to fixing my goof with output_dir:
- removes unnec require in bundle_context
- spec/support/bundle_setup can now rely on bc.progress_log_file
connects to #78 
Closes #317

bundle_context: output_dir REALLY uses project_name

---

Gemfile
Gemfile.lock
config/initializers/okcomputer.rb

Baseline checks are better than none, to start.
Fixes #283

Add okcomputer

---

app/services/discovery_report.rb
spec/services/discovery_report_spec.rb

- Dor::Item find takes in a druid not druid tool object
- empty_object logic was backwards
- 2 RSpec tests to test the fixed logic.
closes #306 
connects #237

empty_object logic fix and Dor::Item find druid fix

---

.travis.yml
README.md
Rakefile
config/database.yml
db/schema.rb
db/scripts/preassembly_setup.sql
db/scripts/preassembly_test_setup.sql

Largely a reversion of "postgres initialization scripts for dev and test"
No initialization (or configuration) is required for prod, because the `database.yml` and database setup itself is performed by Puppet.
Fixes #288

Use sqlite adapter in test and dev.

---

app/services/discovery_report.rb

- made a few changes so when i run discovery_report w/ a SMPL manifest / SMPL project it works.
this is the output i get when running: 
```
irb(main):022:0> discovery_report.process_dobj(first_digital_object)
=> {:druid=>"druid:aa111aa1111", :errors=>{:dupes=>true, :item_not_registered=>true}, :counts=>{:total_size=>31552, :mimetypes=>{"image/jpeg"=>4, ""=>16, "application/xml"=>6, "audio/x-wav"=>8, "audio/mpeg"=>4, "application/pdf"=>2}, :filename_no_extension=>0, :files_in_manifest=>9, :files_found=>9}}
```

Smpl console work

---

README.md

So much to delete:
- Anything describing `bin` scripts or user-facing command-line ops
- Anything referencing deleted options
- Tutorials on RAILS_ENV and `screen` (again, not a CLI app)
- Remediation of objects
- Deletion of objects
- Lyberservices-specific instructions
- Anything invoking `Assembly::Utils`, which is not even a dependency of this codebase anymore!
Corrected:
- Links to example files!
- syntax and organization
There will certainly be more to amend later, but this is a good start.
Connects to #260

Continue purging the README of misleading content

---

spec/jobs/discovery_report_job_spec.rb

This cuts 24 seconds off of a 30 second `rspec` execution.

Mock Jbuilder for discovery_report_job_spec

---

app/views/bundle_contexts/create.html.erb

We can add this or an alternative link back later, but right now the flow is not necessarily going to involve Argo anyway.  If any link "from" Argo opens in a new tab (probably should), then linking back is
less useful than closing the current tab.
Fixes #313

Remove "Return to Argo" button

---

app/lib/pre_assembly/bundle.rb
app/lib/pre_assembly/digital_object.rb
app/models/bundle_context.rb
app/services/discovery_report.rb
spec/lib/pre_assembly/bundle_spec.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/lib/pre_assembly/smpl_spec.rb
spec/models/bundle_context_spec.rb
spec/test_data/input/mock_progress_log.yaml

Extends #338 
`DigitalObject` initialization previously required ugly, error-prone massive Hashes that were almost entirely derived from the `Bundle` initializing it.  Solution: pass the bundle object instead of a proxy. This reduces memory footprint and logical divergence, since the operative data element stays w/ the instance where it lives, instead of having been copied into a hash with *slightly* different naming conventions.
Also:
- removes `unadjusted_container`, which is never any different than `container`
- only 3 `INIT_PARAMS` now
- anything beyond those 3 raises!  No more silent garbage initialization (which was happening in specs!)
- `BundleContext` enums now assume default values upon initialization
- test cleanup with factories and structure
Fixes #271

DigitalObjects.new takes a Bundle, instead of a big hash proxy for a bundle

---

app/services/discovery_report.rb

Not used by anything anymore.
Fixes #341

Remove skipped_files method from discovery_report

---

app/lib/pre_assembly/bundle.rb
app/models/bundle_context.rb
spec/lib/pre_assembly/bundle_spec.rb
spec/models/bundle_context_spec.rb
spec/test_data/exemplar_templates/TEMPLATE.yaml

Follows #373 (one distinct commit)
Fixes #329

remove manifest_cols

---

app/lib/pre_assembly/bundle.rb
app/lib/pre_assembly/object_file.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/lib/pre_assembly/object_file_spec.rb

- make `initialize` signatures compatible and call super, because that's what good subclasses do.
- `exclude_from_content` has a default: `false`
- Use `alias_attribute` instead of custom double-setter method
- only initialize locally the stuff we define locally, the rest is the superclass' domain

Call super in ObjectFile subclass initializer

---

.travis.yml
config/initializers/okcomputer.rb

Largely borrowed from PreservationCatalog
Probably enough to say:
Fixes #339

Add more OkComputer checks

---

app/controllers/bundle_contexts_controller.rb
app/models/job_run.rb
spec/controllers/bundle_contexts_controller_spec.rb
spec/models/job_run_spec.rb

Default the enum value in the model via `after_initialize`, like our other models.   Then just let the BC controller pass a new object directly (it no longer has to know anything about `JobRun` values).
Fixes #382

discovery_report default

---

app/controllers/bundle_contexts_controller.rb
app/controllers/job_runs_controller.rb
app/models/bundle_context.rb
app/views/bundle_contexts/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_header.erb
config/routes.rb
spec/controllers/bundle_contexts_controller_spec.rb
spec/controllers/job_runs_controller_spec.rb
spec/views/bundle_context_spec.rb
spec/views/bundle_contexts/show.html.erb_spec.rb

This is a coherent enough chunk of progress to warrant a PR now.  
- reworks flash notices, for bootstrap styling and better specificity, with close-capability
- add BundleContext show template with tests 
- cleans up some specs
New flash `success` message looks like:
Up next:
- action buttons for "new discovery report" and "new preassembly"
- possible refactor of the BundleContext `<dl>` into a partial, to be used by show page, put also included in `JobRun` show page.
Part of #374

BundleContext show page

---

app/jobs/preassembly_job.rb
app/models/bundle_context.rb

There are 0 FIXME’s left in the code, and about 9 TODO’s left in the code. THe last 9 have to do with using `dor-workflow-service` gem (which i dont think we will get to this cycle) and removing code that is not being used (which we may or may not get to )
closes #355

these fixme and todo's are not needed anymore

---

app/controllers/bundle_contexts_controller.rb
app/controllers/job_runs_controller.rb
app/views/bundle_contexts/show.html.erb
config/routes.rb
spec/controllers/job_runs_controller_spec.rb
spec/views/bundle_contexts/show.html.erb_spec.rb

Complete with route, actions and specs.
Show page for a `BundleContext` with buttons looks like:
Does #374, or as much of it as I think is relevant (that ticket is too expansive).

JobRunsController gets its own create method/route, BC show gets buttons

---

README.md
app/lib/pre_assembly/bundle.rb
app/lib/pre_assembly/digital_object.rb
config/environments/development.rb
lib/dev_shibboleth_headers.rb
spec/lib/pre_assembly/bundle_spec.rb

mainly:
* a bit of rack middleware to set a default sunet_id in dev, and instructions on how to override the default (#323).  ripped off and tweaked from the argo code pointed to by #323.
but also some stuff from my notes (nitpicks to other PRs that i didn't ticket):
* log message for Bundle#run_pre_assembly end, differentiate start/end log messages in that method. tests. (https://github.com/sul-dlss/pre-assembly/pull/346#discussion_r220278499)
* remove defunct comment (https://github.com/sul-dlss/pre-assembly/pull/256/files#r217549930)
fixes #323

default user, and a couple touchups

---

app/models/bundle_context.rb
config/initializers/load_config.rb
config/settings/bundle_dir_roots.yml.erb
spec/models/bundle_context_spec.rb

Hopefully i spelled all of the mounts [here](https://consul.stanford.edu/pages/viewpage.action?title=Content+Mount+Paths&spaceKey=CollAcc) correctly
closes #387

restrict allowable paths for bundle dir input

---

config/initializers/bundle_dir_roots.yml.erb
config/initializers/load_config.rb

bug fix - chomp trailing slash in ALLOWABLE_BUNDLED_DIRS
add dor/staging to production mounts, (union of stage and prod mounts)

Bundle dir staging - chomp trailing slash

---

app/controllers/bundle_contexts_controller.rb
app/views/bundle_contexts/_bundle_context.html.erb
app/views/bundle_contexts/index.html.erb
app/views/bundle_contexts/new.html.erb
app/views/bundle_contexts/show.html.erb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
config/initializers/kaminari_config.rb
config/initializers/load_config.rb
config/routes.rb
spec/controllers/bundle_contexts_controller_spec.rb
spec/views/bundle_contexts/show.html.erb_spec.rb

- buttons are now part of the partial for a BC, meaning they are included via reuse by `JobRunsController#show` and `BundleContextsController#index` here.
- route added
- minimal test
- BC index does pagination when needed
- Kaminari templates and config generated
- Removed double-assignment of a constant.
Looks like:
_________________________________________________________________
Overall, in the future seems like we could use a NavBar with links for:
- "Jobs"
- "Projects"
- "New Project"

BC index, kaminari templates and a bugfix

---

app/views/job_runs/_recent_history.erb
app/views/job_runs/index.html.erb
app/views/job_runs/show.html.erb
app/views/shared/_header.erb
spec/views/shared/_header_spec.rb

-  removes unnecessary links that are now located on the header
- adds Projects, Jobs, and Start a new job to header
- Logo now links to Root and Adds usage info too.
- adds Rspec tests
rebased off master
Looks like this full size:
As we shrink the web page it looks like this:
And then like this:
closes #314 
closes #410

Updates Header w/ useful links and Adds RSpec tests

---

Gemfile
Gemfile.lock

Rails 5.2.2 is incompatible with sqlite 1.4
Refs [rails/rails#35153](https://github.com/rails/rails/issues/35153)

Pin sqlite to ~> 1.3.13

---

README.md
config/deploy/old_prod.rb
config/deploy/old_stage.rb

- updates to readme
- remove ability to deploy v3-legacy branch from master (which doesn't work anymore because of changes in linked files)

changes to readme to reflect how to deploy branches and remove ability to deploy legacy CLI from master

---

Gemfile
Gemfile.lock
lib/pre_assembly/digital_object.rb
spec/digital_object_spec.rb

fixes #473
smoke tested and validated on sul-lyberservices-test

unpin and update dor-services-client, update call

---

app/models/bundle_context.rb
app/views/bundle_contexts/_new_bc_form.erb
spec/models/bundle_context_spec.rb

Changed option text from **SMPL** to **Media** in **Content Structure** and **Content metadata creation** select fields.
For #490

Changed SMPL option for content structure and content metadata creation

---

devel/prepare_content.rb

by request of the maps accessioning team, modify the regex logic of this script to only search for exact matched filenames, but allow them to be in sub-directories of the starting search folder
fixes #504 	
Note, also need to update documentation at https://consul.stanford.edu/pages/viewpage.action?pageId=146704638

modifications to content prep script to search all subdirectories

---

app/lib/pre_assembly/digital_object.rb

https://github.com/sul-dlss/pre-assembly/pull/483 removed DSC from DigitalObject. This line was missed in that PR, I believe.

Remove unnecessary require

---

Gemfile
Gemfile.lock
app/lib/pre_assembly/digital_object.rb
app/models/bundle_context.rb
app/views/bundle_contexts/_new_bc_form.erb
spec/models/bundle_context_spec.rb
spec/test_data/exemplar_templates/TEMPLATE.yaml

~~pre-req: https://github.com/sul-dlss/assembly-objectfile/pull/7~~
addresses #427 and #428
Note that the `assembly-objectfile` gem is actually responsible for creating the contentMetadata, so this just needs to add the type as a selectable option.  Everything else happens in the gem.

add 3d as a valid content type structure

---

Gemfile
Gemfile.lock
config/projects/TEMPLATE.yaml
lib/pre_assembly/bundle.rb

(like #516 but for the v3-legacy branch)
~~pre-req: https://github.com/sul-dlss/assembly-objectfile/pull/7~~
addresses #427 and #428
Note that the assembly-objectfile gem is actually responsible for creating the contentMetadata, so this just needs to add the type as a selectable option. Everything else happens in the gem

adds 3d support for v3-legacy accessioning

---

app/services/discovery_report.rb
spec/services/discovery_report_spec.rb
spec/test_data/media_missing/manifest.csv
spec/test_data/media_missing/media_manifest.csv
spec/test_data/project_config_files/media_missing.yaml

due to Honeybadger https://app.honeybadger.io/projects/52900/faults/46820737
Note:  I am not 100% sure of the error structure.  @jmartin-sul - care to review?

disc report:  get error to user for missing container name or manifest

---

README.md

Now that v3-legacy branch has been move to lyberservices-scripts repo, info about it can be removed from the README.
(Yes it is all in the lyberservices-scripts README.   Feel free to double-check.)

README: remove v3-legacy branch info

---

config/initializers/dor_services_client.rb
config/settings.yml

This is no longer required, and in fact can break the client if the header value (from shared_configs) is unset. This is what broke the workflow service connection to dor-services-app.

Remove token_header keyword arg when configuring dor-services-client

---

Gemfile
Gemfile.lock

One of roo's dependencies, rubyzip has a vulnerability. Since we don't need roo, the best thing to do is remove the dependency.
N/A

Remove unused dependency 'roo'

---

config/environments/production.rb

when updating to i18n v1.1.0, this comes up in bundle install.
```
HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.
Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.
For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
```
This PR adds the change indicated.  default_locale is "en".
n/a

fix config.i18n.fallbacks per instructions

---

Gemfile
Gemfile.lock
spec/controllers/bundle_contexts_controller_spec.rb

Rubocop was quite out of date.
n/a

Upgrade rubocop to the latest version

---

app/lib/pre_assembly/assembly_directory.rb
app/lib/pre_assembly/digital_object.rb
spec/lib/pre_assembly/assembly_directory_spec.rb
spec/lib/pre_assembly/digital_object_spec.rb

DigitalObject has more than one responsibility so it would be easier to understand if some of them were extracted.
n/a

Extract AssemblyDirectory class from DigitalObject

---

app/lib/pre_assembly/digital_object.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/lib/pre_assembly/media_spec.rb

make generate_content_metadata and generate_technical_metadata functional
n/a

Reduce statefullness of DigitalObject

---

.rubocop.yml
app/lib/pre_assembly/digital_object.rb
spec/lib/pre_assembly/digital_object_spec.rb

We don't need to do special coding around parameters, we can use the language constructs (kwargs)
n/a

Simplify the initialization of DigitalObject

---

app/lib/pre_assembly/bundle.rb
app/lib/pre_assembly/copy_stager.rb
app/lib/pre_assembly/digital_object.rb
app/lib/pre_assembly/link_stager.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/lib/pre_assembly/media_spec.rb

In this way staging_style_symlink does not need to be delegated from BundleContext to Bundle to DigitalObject
n/a

Do dependency injection of the stager

---

app/lib/pre_assembly/bundle.rb
app/lib/pre_assembly/digital_object.rb
spec/lib/pre_assembly/bundle_spec.rb

So we don't need so many setters and can just pass the values in when initializing the DigitalObject
n/a

Simplify how DigitalObject is initialized

---

app/lib/pre_assembly/digital_object.rb
app/lib/pre_assembly/media_project_technical_metadata_creator.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/lib/pre_assembly/media_project_technical_metadata_creator_spec.rb
spec/lib/pre_assembly/media_spec.rb

Each class should only have one responsibility. This moves the responsibility for creating techMetadata.xml into it's own class.
n/a

Extract technical_metadata_creation

---

app/lib/pre_assembly/digital_object.rb

Container does not need a writer

---

app/lib/pre_assembly/digital_object.rb

So we don't repeat the process of building the version client
n/a

DRY out create_new_version

---

config/initializers/bundle_dir_roots.yml.erb

authorize a new directory for accessioning

add new bundle path

---

Gemfile
Gemfile.lock

We were previously using a release candidate, not a released version.
n/a

Update shoulda matchers to a released version

---

Gemfile
Gemfile.lock

To be consistent with the rest of the infrastructure portfolio.  Drops old unnecessary dependencies.
n/a

Update dor-services to 8.1

---

app/lib/pre_assembly/bundle.rb
app/lib/pre_assembly/digital_object.rb
spec/lib/pre_assembly/bundle_spec.rb

Bundle is the only thing that needs to know about pre_assem_finished, so keep it there.
n/a

Keep progress separate from the model

---

app/lib/pre_assembly/digital_object.rb
spec/lib/pre_assembly/bundle_spec.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/lib/pre_assembly/media_spec.rb

This makes it easier to understand how outside classes interact with this class
n/a

Make methods that are not part of the interface private

---

app/lib/pre_assembly/digital_object.rb
app/models/bundle_context.rb
app/views/bundle_contexts/_new_bc_form.erb

This object type is deprecated and we don't want any new ones to be created.
Fixes #589 
n/a

Remove book_as_image as an option

---

app/lib/pre_assembly/bundle.rb
app/lib/pre_assembly/digital_object.rb
spec/lib/pre_assembly/bundle_spec.rb
spec/lib/pre_assembly/digital_object_spec.rb

Presently, it just raises an error and the user never sees their job complete.
Fixes #560
n/a

Show an error to the users if their job fails

---

config/deploy.rb

To make it easier to deal with long-running workers when deploying.
no

Use hot-swap to restart workers gracefully

---

Gemfile.lock

bundler v 2.1.2 is the default when you update rubygems for ruby 2.5.3 in rvm.  This update allowed for a clean deploy (though I did have to reinstall ruby 2.5.3 and update rubygems on the VM)
n/a

use bundler 2.1.2 for deployment

---

app/lib/pre_assembly/bundle.rb

closes #603
To prevent log_progress_info from being passed a nil when it expects a hash.
No.

Prevents nil from being passed to log_progress_info.

---

app/lib/pre_assembly/digital_object.rb
spec/lib/pre_assembly/digital_object_spec.rb

Not submitting a version is deprecated
n/a

Submit current version when starting a workflow

---

app/lib/pre_assembly/bundle.rb
spec/lib/pre_assembly/bundle_spec.rb

DO NOT MERGE - I need to tweak this
To surface better information to end users when TypeError is encountered for pre-assembly job due to ensure clause:
which ends up as a failed job in resque (and won't any longer after this PR)
n/a

[DRAFT] avoid 'no implicit conversion of nil into Hash' when pre_assemble doesn't complete

---

app/lib/pre_assembly/bundle.rb
spec/lib/pre_assembly/bundle_spec.rb

To surface better information to end users when TypeError is encountered for pre-assembly job 
I think the TypeError is coming from somehow getting to `log_progress_info` method without status, so this should sew up that hole, too (See PR #611 for another possible hole plugged).
Trying to avoid this:
n/a

bundle.log_progress_info copes with nil status

---

config/initializers/okcomputer.rb

to avoid HTTP 500 errors due to queue depth being > 5.   (Nagios was complaining).
rails logs:
```I, [2020-01-28T16:13:58.702213 #10806]  INFO -- : [44dd7e46-6a77-4601-b68f-b4041808fc5a] Started GET "/status/all" for 171.66.183.13 at 2020-01-28 16:13:58 -0800
I, [2020-01-28T16:13:58.703023 #10806]  INFO -- : [44dd7e46-6a77-4601-b68f-b4041808fc5a] Processing by OkComputer::OkComputerController#index as HTML
D, [2020-01-28T16:13:58.707808 #10806] DEBUG -- :    (0.3ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
I, [2020-01-28T16:13:58.709447 #10806]  INFO -- : [44dd7e46-6a77-4601-b68f-b4041808fc5a]   Rendering text template
I, [2020-01-28T16:13:58.709530 #10806]  INFO -- : [44dd7e46-6a77-4601-b68f-b4041808fc5a]   Rendered text …
```

okcomputer check: increase allowed queue depth to 15 (was 5)

---

app/lib/pre_assembly/digital_object.rb

`book_as_image` is deprecated in assembly-objectfile so we don't want to use this style anymore.
This will simplify the logic and make it possible for us to use the cocina types to determine the project style.
n/a.

Don't pass deprecated options to assembly-objectfile

---

config/initializers/okcomputer.rb

@Mellen22 submits her pre-assembly reports in clumps;  a higher queue size for okcomputer shouldn't alert.
n/a

okcomputer: allow queue depth of 40

---

config/initializers/okcomputer.rb
config/settings.yml

Fixes #628
So nagios doesn't have to specifically check for number of resque workers - developers have more control over number of expected workers.
See 2nd to last line:
in pushing tweaks, i was able to observe "10 out of 5" workers due to hotswap, which quickly settled back to "5 out of 5"
na
Only nagios - i will post in ops when this is deployed to prod.

add okcomputer check for number of workers

---

.travis.yml
config/initializers/okcomputer.rb

Currently the only redis connection the app uses in test is in the initializer, then this is never invoked.  This makes it simpler to test the app.
n/a
no

okcomputer checks: don't connect to Redis unless production

---

.rubocop.yml
app/lib/pre_assembly/batch.rb
app/services/object_file_finder.rb
spec/lib/pre_assembly/batch_spec.rb
spec/services/object_file_finder_spec.rb

Batch has too many responsibilites, this extracts the responsibility for finding the files to it's own class
Fixes #646
no
no

Extract ObjectFileFinder from Batch

---

.rubocop.yml
.rubocop_todo.yml

Exclude testing methods from Metrics/BlockLength

---

app/lib/pre_assembly/batch.rb
app/lib/pre_assembly/digital_object.rb
spec/lib/pre_assembly/batch_spec.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/lib/pre_assembly/media_spec.rb

Previously it was calling dor-services-app twice for each druid to see if it was dark. Now we're caching that value so it only has to call dor-services-app once.
no
yes

Remove a duplicate call to dor-services-app

---

config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/settings.yml

Fixes #609 
This seems like the list impactful way to make this change.
Linked shared_configs: https://github.com/sul-dlss/shared_configs/pull/1336 and https://github.com/sul-dlss/shared_configs/pull/1337
Verified by integration test:
```
Your Preassembly job #216 completed.
You can view the job details and log file at: https://sul-preassembly-stage.stanford.edu/job_runs/216
```
N/A
No.

Add configurable setting for mailer host

---

spec/lib/pre_assembly/batch_spec.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/services/discovery_report_spec.rb

These stubs were unnecessary and misleading.
Test suite
none

Stop stubbing methods that we don't use

---

config/application.rb

This removes the deprecation warning:
```
Sending mail with DeliveryJob and Parameterized::DeliveryJob is deprecated and will be removed in Rails 6.1
```
test suite
n/a

Switch to rails 6.0 defaults

---

.rubocop.yml
app/services/discovery_report.rb
spec/services/discovery_report_spec.rb

Long running discovery report jobs cannot be monitored to see if they are stuck or still running.  This would add a running progress log that could be tailed to monitor progress.
fixes #693
once reviewed, can be deployed to stage and tested there with a discovery report job
none

add progress logging to the discovery report jobs similar to pre-assembly jobs

---

.travis.yml
Gemfile
Gemfile.lock

fix the build to work with latest autoprefixer-rails.
see https://github.com/sul-dlss/pre-assembly/pull/713
* CI
* node has been updated on the VMs, will push to stage to smoke test (though now that i think about it, node was upgraded on prod earlier today, and no complaints yet 🙂)
just travis config

upgrade node in travis to work with latest autoprefixer-rails, unpin autoprefixer-rails

---

Gemfile
Gemfile.lock

Upgrade dor-services-client to get latest cocina models.
Unit
NA

Upgrade dor-services-client.

---

Gemfile
Gemfile.lock

to keep in sync with tiny cocina-models change for a dor-services-app mapping ticket.

update dor-services-client to 6.16

---

.travis.yml
spec/rails_helper.rb

- Fix failing test from Rails 6.1 upgrade
- Remove ruby 2.5.3 from test matrix and add the ruby version currently on the pre-assembly prod server
Unit tests
n/a

fix failing test in rails 6.1

---

README.md
config/deploy.rb

Updates README and deploy config comment to use `main` instead of `master` branch.
Test suite
Yes

Updates README and config to use main instead of master branch

---

Gemfile
Gemfile.lock

Because rails tends to break things even in minor updates
Unit tests
N/A

pin to minor version of rails

---

app/lib/pre_assembly/digital_object.rb

Fixes #743 - ensure agreement objects can accession properly and create the appropriate contentMetadata
See the ticket for details of the investigation/analysis performed.  There is only one change that is needed -- ensuring that agreement type objects get "file" type contentMetadata by mapping the object type "agreement" ==> "file"
Mostly useful when sul-dlss/argo#2687 is also done, but not dependent on it.
In -stage:
- This object was re-accessioned and it now has the newly updated file I added and the `contentMetadata` was correctly set to `file` with the correct `publish/preserve/shelve` attributes for a dark object.  Even though I told it to use `content structure == 'image'` when I setup the job, it correctly deduced this was an agreement, and that it should actually be of type …

agreements should accession in pre-assembly

---

spec/rails_helper.rb
spec/spec_helper.rb

Fixes #825 
This is now required under Rails 7 at least in terms of getting CodeClimate to accurately report test coverage.

Require simplecov before the app

---

config/environments/production.rb

The Rails 7 upgrade mistakenly disable resque as a queue adapter, preventing it from queuing jobs.  This re-enables it.
see https://github.com/sul-dlss/pre-assembly/pull/819/files#diff-da60b4e96eff2b132991226d308949e23f4ef3aad45ad59edd09cbc32cc6251eL62-L64

re-enable resque as the queue adapter

---

bin/prepare_content

This script is used by the Maps team to prepare content for accessioning.  They do not need it to create contentMetadata, so remove this option to avoid future confusion.
The diff looks more complicated than it is -- basically removed mention of this option in the comments/instructions, and removed the `if...then...else` block that used to check if that options was being used to run a different part of the script.

remove unused contentMetadata option from prepare content script

---

app/lib/pre_assembly/content_metadata_creator.rb
app/lib/pre_assembly/object_file.rb
spec/lib/pre_assembly/batch_spec.rb
spec/lib/pre_assembly/content_metadata_creator_spec.rb

Running specs for PR #866, noticed the spec skip message and realized there was more purging of unused code to be done!!!!

remove unused CLI option exclude_from_content

---

app/lib/pre_assembly/assembly_directory.rb
app/lib/pre_assembly/digital_object.rb

Fedora3 and datastreams are no more in the SDR.  Long live the SDR!

remove references to Fedora datastream concept

---

Gemfile
Gemfile.lock
app/jobs/discovery_report_job.rb
app/jobs/preassembly_job.rb
app/lib/pre_assembly/batch.rb
app/lib/pre_assembly/digital_object.rb
app/models/job_run.rb
app/views/job_runs/_recent_history.erb
app/views/job_runs/index.html.erb
app/views/job_runs/show.html.erb
db/migrate/20220531215736_add_job_status.rb
db/schema.rb
spec/factories/job_runs.rb
spec/jobs/discovery_report_job_spec.rb
spec/jobs/preassembly_job_spec.rb
spec/lib/pre_assembly/batch_spec.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/mailers/job_mailer_spec.rb
spec/models/job_run_spec.rb
spec/views/job_runs/show.html.erb_spec.rb

Fixes #535 and fixes #532 and fixes #695, specifically:
- rescue exceptions that occur when processing a single object on preassembly jobs and allow them to continue....previously an exception when processing an object would just cause the job to fail, with no visible indication in the UI...it would just appear to be running forever when it might have failed on the first object
- track the status of the job run in database state using a state machine (instead of relying on the existence of a progress log file) and use this when showing status to the user
- preassembly jobs will now be marked as complete if all objects succeed or marked as error if there was at least one object that threw an exception (status will also show if still running)
- email notifications will occur when the job …

add job run state and catch exceptions

---

app/controllers/job_runs_controller.rb
app/jobs/preassembly_job.rb
app/models/job_run.rb
app/views/job_runs/show.html.erb
config/routes.rb
spec/controllers/job_runs_controller_spec.rb
spec/jobs/preassembly_job_spec.rb
spec/test_data/input/mock_discovery_report.json
spec/views/job_runs/show.html.erb_spec.rb

Fixes #939 
- correctly label report download link for discovery report
- allow user to download discovery report log file (like they do for preassembly jobs)
- behavior for pre-assembly jobs is unchanged
Currently discovery reports have a link that says "Job output Log", but it's really the report itself in JSON format. There is no way to actually get the log.
Show both the report and the log, correctly labelled.
Updated tests

Allow user to download log for discovery reports; better labels

---

app/views/job_runs/recent_history.html.erb

Follow up from #960 -- missed one spot in the UI in that PR to show the friendly state name to the user (recent history)
Localhost

show friendly state name in recent history

---

app/views/job_runs/_job_runs.html.erb
app/views/job_runs/index.html.erb
app/views/job_runs/recent_history.html.erb

Now that we are using turbo instead of javascript for recent history, we can use a partial instead of duplicating that code.
Also, we need to tell turbo to replace the entire page when viewing job run detail pages (else you will get odd behavior from the recent history panel).
Localhost

refactor job display, fix turbo issue

---

app/lib/pre_assembly/batch.rb

Found this now unused method while doing #945
Existing tests

remove unused method

---

app/services/discovery_report.rb
spec/services/discovery_report_spec.rb

Fixes #917 -   log individual object errors in the yaml log file for discovery report
Updated tests

discovery report yaml log file should log objects that have an error

---

app/assets/stylesheets/application.css
app/views/batch_contexts/_batch_context.html.erb

**Holding for PO review**
Fixes #492, which requested the button colors be changed.
locally, unit tests, integration test, Andrew.

make all buttons cardinal-red

---

app/assets/stylesheets/application.css

So we only need to define it in one place and we can use it everywhere. The variable name is easier to understand than an hex code.  Also fixed a contrast issue on hover.
locally

Create a cardinal-red css variable

---

app/views/shared/_header.html.erb

Update to bootstrap 5 broke the close button on alert dialogs - this fixes it
Localhost

fix bootstrap close alert

---

app/assets/stylesheets/application.css
app/views/shared/_header.html.erb
spec/views/shared/_header_spec.rb

Tighten up the brand bar

---

app/jobs/discovery_report_job.rb
app/jobs/preassembly_job.rb
app/lib/pre_assembly/batch.rb
app/models/job_run.rb
app/services/discovery_report.rb
app/views/job_runs/show.html.erb
db/migrate/20220607221157_error_message.rb
db/schema.rb
spec/jobs/discovery_report_job_spec.rb
spec/jobs/preassembly_job_spec.rb
spec/lib/pre_assembly/batch_spec.rb
spec/models/job_run_spec.rb
spec/services/discovery_report_spec.rb
spec/views/job_runs/show.html.erb_spec.rb

Todo:
Fixes #945 and fixes #936:
- store any errors that occurred during processing in the database so we can show to the user (for both pre-assembly and discovery jobs)
- put discovery report and pre-assembly jobs into an error or failure state based on if individual objects had an error or the whole job failed
Example error message display to user on detail page:
New tests

store errors in the job run and show to the user

---

config/environments/test.rb

(attempt for) Fixes #980 
If this doesn't work, next step is to increase the timeout in database.yml for the test environment (another suggestion from the rails ticket referenced in the comment: https://github.com/rails/rails/issues/30937, and elsewhere).
Existing tests

attempt to deal with sqlite locking in tests

---

app/lib/pre_assembly/batch.rb
spec/jobs/preassembly_job_spec.rb
spec/lib/pre_assembly/batch_spec.rb
spec/support/batch_setup.rb

A lot of the "public" interface of `batch.rb` doesn't need to be public.  This is a beginning of removing unused attributes and delegations as well as making methods only used by the Batch class private.
There are more methods to be made private, but I wanted to get a PR of progress so far up and merged.

batch.rb: shrink public attrs and methods

---

app/views/job_mailer/completion_email.text.erb
spec/mailers/job_mailer_spec.rb

Fixes #976 - add the final state of the job in the notification email (e.g. "completed", "failed", etc.)
Updated test

add job state to notification email

---

app/models/job_run.rb
app/views/job_runs/show.html.erb
spec/controllers/batch_contexts_controller_spec.rb
spec/factories/batch_contexts.rb
spec/factories/job_runs.rb
spec/lib/pre_assembly/batch_spec.rb
spec/lib/pre_assembly/digital_object_spec.rb
spec/models/batch_context_spec.rb
spec/views/job_runs/show.html.erb_spec.rb

1. The condition under which we show the discovery report link was in the view ... this makes it easier to understand and puts it in the model.
2. Re-running individual specs could sometimes fail when a test directory was not cleaned up correctly, this just forces cleanup even if the directory is not empty (using `FileUtils.remove_dir`, which is also used elsewhere in the tests instead of `Dir.delete`)
3. Changing some fixture data and mocking to better reflect the actual differences between preassembly and discovery_report jobs in the database.  It doesn't currently affect existing tests, but could become a source of unexpected test behavior in future tests.
Localhost

refactor display of reports; fix cleanup of non-empty directories

---

config/environments/test.rb

i too was hitting the annoying SQLite contention errors fixed by #982.  but then i also noticed a big increase in the time it took the test suite to execute once i rebased my WIP on that fix.  i went to look into alternate test adapters after @jcoyne mentioned the `:test` adapter.  i didn't end up going that route, but i did come up with a tweak that i think addresses both the SQLite contention issue and the slow test execution (and brings back the benefit that the default `:async` adapter gives in terms of test quality).  explained in the config comment.
local test suite execution.  across 4 or 5 runs, i noticed the tests running at their old speed, and i also ran into no SQLite errors.
⚡ ⚠ If this change has cross service impact (e.g. changes what is written to shared file systems or …

speed up test execution while avoiding SQLite contention issue

---

lib/tasks/reports.rake

To help with #948 - add a rake task to run analytics of the discovery reports.  Note that we are counting on the JSON files still being on disk (of which most still seem to be).  It outputs a single CSV file with one row per discovery report it was able to analyze with the following columns:
- num_objects (total number of objects in report)
- num_files   (total number of files in report)
- num_errors  (number of objects in error)
- runtime_minutes (total runtime in minutes)
- user (user that ran the report)
- report_date (date the report finished)
We can use this CSV file to do plots in Excel.
On stage, which has actual data

add a rake task to run analytics on discovery reports

---

app/services/discovery_report.rb
spec/features/discovery_report/build_manifest_image_spec.rb
spec/features/discovery_report/file_manifest_book_spec.rb
spec/test_data/input/mock_discovery_report.json

While working on #948, I was starting to examine the YAML progress log files to see if they could mined for information.
1. I noted that we use the same log file for both discovery reports and pre-assembly jobs for the same BatchContext (e.g. project).  This is fine and works with the existing code for restarting a pre-assembly job, but I thought it would be useful to explicitly indicate for each druid in the log file which type of job the log entry was for.  We do this for pre-assembly jobs already (which is how we use this YAML file for restarting pre-assembly jobs), but we don't do it for discovery report jobs.  This adds info the existing log entry.  It has no user interface impact, but would be useful for implementing restarting of discovery jobs or analysis using the YAML files. …

add info to progress log file for discovery reports

---

app/lib/pre_assembly/batch.rb
spec/features/preassembly_run/no_files_spec.rb

Fixes #998 - when a pre-assembly job runs and an object has no files, this is marked as "success" (current behavior), but should not put the job run into a "completed (with errors)" state, but instead should just be "completed" (new behavior).
Update the recently added integration test to verify these jobs end in a completed state with no error.
~~Wait until #997 is merged, rebased here and then updated to reflect this new behavior~~
Updated existing test from #997 (that new test started failing with my code change here until I adjusted the test)

objects with no files should complete the pre-assembly job successfully

---

Gemfile
Gemfile.lock

It turns out that pre-assembly doesn't create images.   Who knew?
If you're dubious, do a search on "image" in the app directory.
It does make me wonder how long this has been true ...
unit tests, and for good measure, I deployed this branch on qa and ran the integration test that uses pre-assembly.

remove unused assembly-image gem

---

app/lib/pre_assembly/object_file.rb

assembly-objectfile will soon not have the module named Assembly::ObjectFileable
it was a comment change.

remove reference to Assembly::ObjectFileable

---

Gemfile.lock
app/lib/pre_assembly/batch.rb
app/services/discovery_report.rb
app/services/object_file_validator.rb
spec/lib/pre_assembly/batch_spec.rb
spec/services/discovery_report_spec.rb

closes #961
* Batch#digital_objects, Batch#un_pre_assembled_objects, and Batch#containers_via_manifest now all return an Enumerator, instead of loading all their respective arrays into memory at once and memoizing the result
* DiscoveryReport#each_row now yields a lighter-weight hash, instead of an ObjectFileValidator instance, since the validator's hash represenation was the only part of the result being used anyway (for JSON serialization).
it surprised me somewhat, and i can't explain why exactly, but the second change was as important as the first: the first allowed a discovery report for which memory usage ballooned past 6 GB (before being killed for using too much memory) to run for longer and balloon less quickly; the second change in conjunction with the first allowed the same …

tweak object instantiation and iteration to reduce discovery report peak memory consumption

---

app/lib/pre_assembly/digital_object.rb
spec/lib/pre_assembly/batch_spec.rb
spec/spec_helper.rb

* pro: this makes the tests more concise and adds a possibly useful equality checking method
* con: i'm not sure that this is actually captures the desired semantics of `DigitalObject#==`.  also, only the tests use it at present.  i think the comparison works for the tests, but for example, should it rely on the default instance-equivalence equality check for `Batch`, or should `Batch` be compared for semantic equality between possibly different instances instead?
unit tests

define DigitalObject#==, let it be used implicitly in test comparisons

---

README.md
docker-compose.yml

Installing redis in order to manual run the server differs from our normal practice of starting external dependencies using docker compose. This moves that dependency into the `docker-compose.yml` file and updates the README to reflect these changes.

Add redis to docker compose and update readme

---

app/lib/pre_assembly/from_staging_location/file_set.rb

This constant was not defined in the code, but used when a 3d object is provided.

Add missing constant

---

.circleci/config.yml

The code no longer swallows errors when exiftool is not present:
https://github.com/sul-dlss/assembly-objectfile/commit/db015d5b85a5ab47de5d8d8f131afd38c4e70088
ci

Install exiftool

---

README.md
app/lib/pre_assembly/digital_object.rb
app/lib/pre_assembly/from_staging_location/file.rb
app/lib/pre_assembly/from_staging_location/file_set_builder.rb
app/lib/pre_assembly/from_staging_location/structural_builder.rb
spec/lib/pre_assembly/from_staging_location/structural_builder_spec.rb
spec/services/object_file_finder_spec.rb
spec/test_data/exemplar_templates/TEMPLATE.yaml

"bundle" was a confusing name in this repo due to the use of the "bundler" gem.  This PR renames variables and such to be more meaningful.
There are a few other bonus improvements, like getting rid of unused keyword params.
unit tests

remove remaining usage of "bundle" 

---

app/jobs/discovery_report_job.rb
app/jobs/preassembly_job.rb

Setting a queue is unnecessary because we don't segregate workers by queue. This makes it slightly simpler.
CI

Put all jobs on the default queue

---

app/jobs/discovery_report_job.rb
app/jobs/preassembly_job.rb
spec/jobs/discovery_report_job_spec.rb
spec/jobs/preassembly_job_spec.rb

When a job fails, let's log the full exception with name and message in the database for display to the user.
Updated tests.

log the full exception with name and message when job fails

---

app/lib/pre_assembly/file_manifest.rb
app/lib/pre_assembly/from_file_manifest/structural_builder.rb
app/services/object_file_validator.rb
spec/lib/pre_assembly/from_file_manifest/structural_builder_spec.rb

This keeps us from having to do two passes over the data and eliminates a complex method.

[refactor] Load manifest into a tree structure

---

app/lib/pre_assembly/file_manifest.rb
app/lib/pre_assembly/from_file_manifest/file_set_builder.rb
app/lib/pre_assembly/from_file_manifest/structural_builder.rb
spec/features/preassembly_run/book_using_file_manifest_spec.rb
spec/features/preassembly_run/media_audio_spec.rb
spec/features/preassembly_run/media_video_spec.rb
spec/lib/pre_assembly/file_manifest_spec.rb
spec/lib/pre_assembly/from_file_manifest/structural_builder_spec.rb

Move it up to the FileManifest.  This will allow us to use the cocina model as the intermediate representation rather than have a hash based representation.

[refactor] Move manifest building out of the structural builder

---

app/lib/pre_assembly/file_manifest.rb

We never end up using this attribute.

Remove the thumb attribute, it's no longer used

---

app/models/job_run.rb

Otherwise the worker can start, but it can't load the JobRun record
Fixes #1064 

Don't enqueue a job until the transaction is committed

---

bin/prepare_content

Allow prepare-content script to deal with BOM encoding.  Similar fix to what was done here: https://github.com/sul-dlss/argo/commit/95bff1dc7980ba563fd568ed5ad2496308017571
Based on an error report from Meagan Trott, which upon investigation turned out to be a CSV file with this encoding pattern.
Ran on localhost with the "bad" CSV and it worked.

update-prepare-content script to deal with BOM encoding issues

---

app/views/batch_contexts/_new_bc_form.erb

After talking to @andrewjbtw , the staging symlink option may be unnecessary/undesirable.  Before removing entirely until we are really sure, we can simply hide it and set to false as default.
Localhost

hide staging symlink option in pre-assembly; defaults to false

---

bin/prepare_content

Symlinking files generated by the prepare content script run by the accessioning team causes problems in technical metadata, this changes the symlink to a copy when staging content (but retains the option to symlink if needed in the future for some reason).  Symlink was only used originally due to disk space constraints, which may no longer be an issue.
Localhost laptop run

change symlink to copy, add option to symlink

---

.solr_wrapper.yml

clarifies there is no use of Solr in preassembly;  makes code base smaller.

remove unused .solr_wrapper.yml

---

config/initializers/dor_services_client.rb
config/settings.yml

Do this because it is the convention we use and also because it matches shared_configs.

Use lower-case settings

---

app/models/batch_context.rb
spec/controllers/batch_contexts_controller_spec.rb
spec/models/batch_context_spec.rb

Fixes #1158 - if user selects media content type, they must include a file manifest
Validate on form submission, so it is not possible to proceed unless the user selects the checkbox (which will then also validate the file exists).  This is a simple server side only approach that does not require any javascript libraries or complications to auto-check the box if the user selects media.
Localhost and new unit test

selecting media content structure requires a file manifest

---

.circleci/config.yml
README.md
Rakefile

Trying to get the right, current mix of tasks, which is hard because there are many and they change.
local tests, CI
Nope.

Use test:prepare task for handling JS and CSS builds

---

README.md
config/initializers/byebug.rb

Initializes the remote byebug server port to follow the pattern used in other reports (i.e. argo)

Initialize remote byebug for debugging

---

app/jobs/discovery_report_job.rb
app/jobs/preassembly_job.rb
app/lib/pre_assembly/batch.rb
app/models/job_run.rb
config/locales/en.yml
db/migrate/20230909033128_add_state_nuance_to_job_runs.rb
db/schema.rb
spec/features/discovery_report/completed_with_errors_spec.rb
spec/features/preassembly_run/no_files_spec.rb
spec/jobs/discovery_report_job_spec.rb
spec/jobs/preassembly_job_spec.rb
spec/mailers/job_mailer_spec.rb
spec/models/job_run_spec.rb
spec/views/job_runs/show.html.erb_spec.rb

* splits `:complete` into `:discovery_report_complete` and `:preassembly_complete`, to differentiate from `:accessioning_complete` (which pre-assembly will start using to track and notify about the eventual completion of accessioning launched by each preassembly `JobRun`)
* for parity with those new states, splits `:complete_with_errors` into `:discovery_report_complete_with_errors` and `:preassembly_complete_with_errors`
* migrates existing `job_runs.state` values using combo of `state` and `job_type`
* provides a reverse migration that goes back to the old state values
fixes https://github.com/sul-dlss/pre-assembly/issues/1198
i dumped a copy of the stage database and then loaded it up on my local preassembly PG instance:
from preassembly stage, after `ksu`ing to root (file ends up in …

better differentiation of JobRun.state values

---

app/views/shared/_header.html.erb

Fixes #1256 
Used Mac VoiceOver to confirm that image was skipped over.
None further.

Alt text for bookshelf image

---

app/views/batch_contexts/_new_bc_form.erb
config/initializers/simple_form.rb

Fixes #1257 to add a label field for the `I have a file manifest checkbox`
Resulting HTML generated:
```
<fieldset class="form-group boolean optional batch_context_using_file_manifest">
<div class="form-check"><input name="batch_context[using_file_manifest]" type="hidden" value="0" autocomplete="off" />
<input class="form-check-input boolean optional" type="checkbox" value="1" name="batch_context[using_file_manifest]" id="batch_context_using_file_manifest" />
<label class="form-check-label boolean optional" for="batch_context_using_file_manifest">I have a file manifest</label>. </div>
</fieldset>
```
Doesn't look like it negatively affects radio buttons on the form. 
AXE DevTools confirms issue has gone away. Mac VoiceOver reads label.
None further, see above.

Label on checkbox

---

app/lib/pre_assembly/file_manifest.rb
app/lib/pre_assembly/from_file_manifest/file_set_builder.rb
app/lib/pre_assembly/from_file_manifest/structural_builder.rb
spec/features/preassembly_run/book_using_file_manifest_spec.rb
spec/features/preassembly_run/hierarchial_files_with_manifest_spec.rb
spec/features/preassembly_run/media_audio_spec.rb
spec/features/preassembly_run/media_video_spec.rb
spec/lib/pre_assembly/from_file_manifest/structural_builder_spec.rb

closes #1240
To avoid having to stage all files to re-accession.
Unit, infra integration

Adds support for targeted file updates.

---

app/models/batch_context.rb
app/models/job_run.rb
app/views/batch_contexts/_batch_context.html.erb
app/views/job_runs/show.html.erb

Fixes #1266 - do not show progress log file on individual job run pages as it can be confusing (a single batch context shares the same progress log file across multiple job runs).  Instead, show it on the batch context page.
It is still available from download from either page (just as before).
Localhost and CI

move inline display of progress log file from job run page to batch context (project) page

---

app/assets/stylesheets/sulFooter.scss

Fixes #1275 - remove underlines from links in footer, show them on hover (just like we do in H2 and similar to Argo, which is where we took default styling from...except Argo does not show underlined links anywhere, so it disables globally)
**BEFORE**
**AFTER**
(hovering over My Account)
Localhost

make footer styling look more like Argo and H2

---

app/jobs/job_run_complete_job.rb
app/jobs/preassembly_job.rb
app/models/job_run.rb
spec/factories/job_runs.rb
spec/jobs/job_run_complete_job_spec.rb
spec/jobs/preassembly_job_spec.rb

closes #1201
To update the state of job run based on updates to accessions.
Unit

Implement job run complete job.

---

app/jobs/job_run_complete_job.rb
app/jobs/preassembly_job.rb
spec/jobs/job_run_complete_job_spec.rb

To avoid a race condition where accessions complete before the job run is marked complete.
Unit

Tweak to job run complete job to avoid race condition.

---

app/lib/pre_assembly/from_staging_location/file.rb
app/lib/pre_assembly/from_staging_location/file_set.rb
app/lib/pre_assembly/from_staging_location/file_set_builder.rb
app/lib/pre_assembly/from_staging_location/structural_builder.rb
app/models/batch_context.rb
app/views/batch_contexts/_new_bc_form.erb
spec/lib/pre_assembly/from_staging_location/structural_builder_spec.rb
spec/models/batch_context_spec.rb

Fixes #1187 
This adds the processing configuration option for `filename_with_ocr`.
Held for testing by @andrewjbtw 

Group by filename with OCR

---

app/controllers/job_runs_controller.rb

Fixes #1283 - the move from a partial to a turbo frame left out this change, which is needed to show the structural differences in the discovery report when they exist
Localhost

show structural changes from discovery report

---

app/models/globus_destination.rb
config/settings.yml
spec/factories/globus_destination.rb
spec/models/globus_destination_spec.rb

Refs #1188 to set up globus destination methods. 
Added unit tests
No, all backend

Adds globus destination helper methods

---

app/models/globus_destination.rb
spec/models/globus_destination_spec.rb

Refs #1188. Adjusts the path in globus to not include the directory where globus is mounted. Adds staging_location method.
Unit.

Add globus staging location and adjust destination path

---

app/views/job_runs/_job_runs.html.erb
app/views/job_runs/index.html.erb
app/views/job_runs/recent_history.html.erb

Fixes #1298 - remove the links to the project from the list of job runs, it's too busy
Localhost

remove link to project from job runs list page

---

app/services/discovery_report.rb
app/services/structural_files_differ.rb
spec/services/discovery_report_spec.rb
spec/services/object_file_validator_spec.rb

closes #1303
The structure diffing assumed the object could be retrieved from dor-services-app.
Unit, stage

Allow discovery report to handle unregistered items.

---

app/views/job_mailer/completion_email.text.erb
app/views/job_runs/_details.html.erb
app/views/job_runs/_job_runs.html.erb

Make all state names appear the same.  Not sure why `.human_state_name` seemed to capitalize some, but not others.  This just makes them all start with a capital letter.
Localhost

capitalize state name for display

---

app/views/job_runs/_structural_updates_summary.html.erb

Fixes #1310 - if a discovery report has file differences but one druid does not have any, you would get an exception like below, which causes the view to not render at all in the turbo frame.  This fixes it by skipping over any druids in the report that do not have a file diffs section in the JSON.
```
| Completed 500 Internal Server Error in 205ms (ActiveRecord: 4.5ms | Allocations: 7934)
15:25:30 web.1  |
15:25:30 web.1  |
15:25:30 web.1  |
15:25:30 web.1  | ActionView::Template::Error (undefined method `[]' for nil:NilClass):
15:25:30 web.1  |     11:     <tbody>
15:25:30 web.1  |     12:     <% druids.each do |druid| %>
15:25:30 web.1  |     13:         <% %w[added_files deleted_files updated_files].each do |status| %>
15:25:30 web.1  |     14:         <% …
```

skip over druids that do not have any file differences

---

app/jobs/discovery_report_job.rb
app/jobs/preassembly_job.rb
app/models/job_run.rb
db/migrate/20230925202808_update_job_run_state.rb
db/schema.rb
spec/features/discovery_report/completed_with_errors_spec.rb
spec/jobs/discovery_report_job_spec.rb
spec/jobs/preassembly_job_spec.rb
spec/models/job_run_spec.rb
spec/views/job_runs/show.html.erb_spec.rb

closes #1301
Make error state less confusing to users. This approach separates the presence of errors from the state.
Unit, Andrew

Remove error as separate job run state.

---

app/jobs/job_run_complete_job.rb
spec/jobs/job_run_complete_job_spec.rb

[HOLD] Transition job run to preassembly_complete_with_errors when all associated accessions failed

---

app/controllers/batch_contexts_controller.rb

Sort all project desc by date

---

app/views/batch_contexts/_actions.html.erb
app/views/batch_contexts/_details.html.erb
app/views/batch_contexts/_jobs_summary.html.erb
app/views/batch_contexts/_settings.html.erb
app/views/batch_contexts/show.html.erb
spec/views/batch_contexts/show.html.erb_spec.rb

Closes #1325 
This just changes the layout of the existing data.
Before:
After:

Reformat projects show page to match job runs show

---

app/mailers/job_mailer.rb
spec/mailers/job_mailer_spec.rb

Fixes #1335 and fixes #1336 - change the subject line of emails sent when jobs complete
CI

change subject lines of completion emails

---

app/views/job_runs/discovery_report_summary.html.erb

Fixes #1334 - swap order of sections on job run page
Localhost

move structural updates summary to bottom of job run detail page

---

app/lib/pre_assembly/digital_object.rb
app/services/object_file_validator.rb

Mostly fixes #1293. A warning still occasionally shows up, but much much less frequently. 
Unit. 
No

Don't re-use client

---

app/controllers/globus_controller.rb
app/javascript/controllers/globus_controller.js
spec/features/batch_context/globus_spec.rb

Adjust the globus controller to check how many globus destinations a
user has already prior to creating another one. If they have 99 or more
the controller returns an JSON error message with 400 status code.
The Stimulus controller checks the response and replaces the Create
Globus Link button with the error message if it's a 400. If it's another
type of error (potentially a 500 error with no JSON body) it uses the
generic message 'Unexpected Globus Error'.
closes #1340
⚡ ⚠ Please ensure this change does not introduce …

Display Globus errors

---

app/models/job_run.rb
spec/models/job_run_spec.rb

closes #1345
To avoid probable race condition in which email was being created before job run object was persisted.

Switch to delivering mail now.

---

lib/tasks/globus.rake

Resolves #1287 to create a rake task to delete access to globus destinations and delete empty directories.
Local and QA

Rake task to remove globus access rules and empty locations

---

app/models/batch_context.rb
app/views/batch_contexts/_settings.html.erb
app/views/batch_contexts/index.html.erb
spec/factories/batch_contexts.rb
spec/factories/globus_destination.rb
spec/models/batch_context_spec.rb
spec/views/batch_contexts/index.html.erb_spec.rb
spec/views/batch_contexts/show.html.erb_spec.rb

Fixes #1276 - display the globus URL in batch_context show and index pages.
Note that the index page would get cluttered with long URLs shown in browser, so I switched to showing "globus link" in that case (see below).  Also note that this doesn't affect the Job Run page (which also shows some batch context details)... we could add it there too, or in fact, just consolidate the partials so they are always the same.  This is done in #1347 (which would then add the globus link to the settings part of the job runs detail too automatically).
Localhost and new tests

show globus links on batch_context show and index pages

---

app/models/globus_destination.rb
spec/models/globus_destination_spec.rb

Depending on how the user arrives at Globus (either from Preassembly, or from the Globus email, or navigating directly themselves) the Globus path embedded in the URL could be in either the `destination_path` or
`origin_path` parameters.
This commit adds the ability to use the Globus Destination ID configured in app settings to infer where to look for the Globus path.
Fixes #1333
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a …

Use globus endpoint id to extract path from URL

---

app/assets/stylesheets/main.scss
app/javascript/controllers/copy_controller.js
app/views/batch_contexts/_settings.html.erb
spec/views/batch_contexts/show.html.erb_spec.rb

Mostly resolves #1352. Whitespace will no longer get added to copied staging location text with the exception of Chrome when there is also a Globus URL.
Local deploy
VoiceOver doesn't indicate any content reading changes.

Remove trailing whitespace when copying location

---

app/views/batch_contexts/_new_bc_form.erb
config/settings.yml
config/settings/test.yml

Don't display the Request Globus Link button if Settings.globus.enabled is false. It defaults to false, and will be enabled in QA and Stage as shared_configs PRs.
Fixes #1357
Local dev.

Globus feature flag

---

app/assets/stylesheets/main.scss
app/views/batch_contexts/_settings.html.erb

Resolves #1361 to not overflow table cell with long staging locations. HOLD in case @andrewjbtw would like to see it with various staging locations in QA/stage. 
Will break the path to fit in the cell:
If a path is just short enough that it fits but the copy icon does not, in Chrome (but not Firefox) it looks like this:
Example reported by @andrewjbtw, now fixed:
Local. 
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See …

Control wrapping of location

---

Capfile
Gemfile
Gemfile.lock
app/models/globus_destination.rb
app/services/globus_cleanup.rb
config/deploy.rb
config/schedule.rb
config/settings.yml
lib/tasks/globus.rake
spec/factories/batch_contexts.rb
spec/factories/globus_destination.rb
spec/factories/job_runs.rb
spec/models/globus_destination_spec.rb
spec/services/globus_cleanup_spec.rb

Fixes #1189 - job to cleanup globus destinations
See https://github.com/sul-dlss/shared_configs/pull/2078 for the HB checkin key for prod
~~Question: do we still need `lib/tasks/globus.rake` after this done?~~ yes we do
Updated tests
Tested in QA

add cleanup job for globus destinations

---

app/controllers/batch_contexts_controller.rb
app/models/globus_destination.rb
spec/features/batch_context/globus_spec.rb
spec/models/globus_destination_spec.rb

Fixes #1368 - if a user creates a Globus Destination and then has a validation error, the "Staging location" will show the full path and not the URL anymore.  When they submit the job, the globus destination will then not be connected to the batch context.  This fixes it by allowing the batch context to be connected to a globus destination either via globus URL or destination path.
~~[HOLD] for testing on QA~~
New integration test.
QA

connect batch context to globus destination via path

---

app/models/batch_context.rb
app/models/globus_destination.rb
app/services/globus_cleanup.rb
spec/factories/batch_contexts.rb
spec/factories/globus_destination.rb
spec/models/batch_context_spec.rb
spec/models/globus_destination_spec.rb
spec/services/globus_cleanup_spec.rb

Previous work in #1354 cleans up Globus destinations that were created more than 1 week ago for completed accessioning jobs .  Discussion with Andrew indicates we should also cleanup disconnected Globus destinations that are more than 1 month old.  These are destinations that were created but for which an associated job was never even created.
This PR adds that second form of cleanup to the first.
There is also a previously created rake task that clears ALL Globus destinations for a specific user, but the hope is that this is a last resort that would not be needed if we perform these automated cleanups.  See https://github.com/sul-dlss/pre-assembly/blob/main/lib/tasks/globus.rake
~~HOLD for testing on QA~~
New specs and tested on QA

cleanup unused and disconnected globus destinations

---

app/views/job_runs/discovery_report_summary.html.erb

closes #1376
Legacy reports had an integer for the errors, instead of an array.

Handles legacy discovery reports.

---

app/lib/pre_assembly/assembly_directory.rb
spec/features/preassembly_run/geo_spec.rb
spec/lib/pre_assembly/assembly_directory_spec.rb

Fixes #1410 by removing the machinery that cares about gis `temp` and druid directories in favor of the standard druid trees and `content` path. The remaining GIS specific code is required in order to start `gisAssemblyWF` instead of accessioning.
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessib …

Align gis staging paths with existing pre-assembly structure

---

app/assets/stylesheets/main.scss

Fixes #1424 
https://github.com/twbs/bootstrap/commit/9a1f4ed9e5cba6424247928b786858edd38223da is believed to have caused the change described in the ticket. This switches `:root` to `.btn` to apply the correct css styling.
stage review
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) …

[HOLD] Switch :root to .btn to fix color contrast regression

---

app/assets/stylesheets/main.scss

Follow up to #1425  to set and use `--bs-btn-bg`

Set and use --bs-btn-bg

---

app/helpers/application_helper.rb
app/javascript/controllers/ocr_controller.js
app/lib/pre_assembly/digital_object.rb
app/models/batch_context.rb
spec/features/preassembly_run/book_using_file_manifest_spec.rb
spec/lib/pre_assembly/digital_object_spec.rb

Fixes #1451 
We do not need to ask pre-assembly users which order (ltr or rtl) their book is in, since this is set at registration time and placed into cocina.  We can use this value from cocina instead when building the rest of the structural.
~~HOLD to run on QA with integration tests~~
~~Note: requires https://github.com/sul-dlss/cocina-models/pull/715 and then bump to a new release to get the specs to work~~
Unit tests.  
~~Should deploy to QA and run integration tests too.~~

remove book order UI option and get from cocina

---

config/deploy.rb

Also, this will break deploys when we move off of the Capistrano-OneTimeKey gem.

Comment out ancient settings that are no longer needed

---

app/views/batch_contexts/_alert.html.erb
app/views/batch_contexts/_new_bc_form.erb

Alternate approach to keep all text in the partial for consistency and pass in a key to decide which to show.
Localhost

move all alert text to partial for consistency

---

app/assets/stylesheets/palette.scss
app/views/batch_contexts/_alert.html.erb
app/views/batch_contexts/_new_bc_form.erb
app/views/layouts/application.html.erb

1476 form redesign

---

Capfile
Gemfile
Gemfile.lock

This commit removes capistrano-rvm, which we no longer need. This is the only app in our portfolio that still uses it. I suspect we missed this when we nuked it a couple years ago. Plus, it breaks SSH stuff in dlss-capistrano 5.1.x.
CI

Ditch capistrano-rvm

---

bin/prepare_content

This dependency is moving out of stdlib in Ruby 3.4 so it must be managed by bundler.
CI

Add csv dependency to bundler

---

.rubocop.yml

Enable Gemspec/AddRuntimeDependency to quiet warning

---

Rakefile
app/helpers/application_helper.rb
app/views/batch_contexts/_new_bc_form.erb

make things a bit more maintainable
ran `bundle exec rake` locally.  existing tests passed, both rubocop and rspec ran by default.
n/a

touchups for readability and usability

---

app/javascript/controllers/caption_controller.js
app/models/batch_context.rb
app/views/batch_contexts/_new_bc_form.erb
spec/models/batch_context_spec.rb

Fixes #1538 - if the user selects "media" as the content structure, hide the "Do you have a file manifest?" question and just mark it as "yes".  If the `file_manifest.csv` is missing, the user will still get a validation error.
**Non-media type (still get the option)**
**Media type (no option)**
Localhost and updated spec.

do not bother asking the user if a file manifest is supplied for media type

---

config/deploy.rb

closes #1531
So that rabbit bindings are set on deploy.
QA

Run rabbitmq setup on deploy.

---

app/javascript/controllers/copy_controller.js

closes #1558
Stop using popovers.
Local

Stop using popovers for copy indicator.

---

app/lib/pre_assembly/from_file_manifest/structural_builder.rb

Add comment to clarify external identifier generation. See https://github.com/sul-dlss/purl/issues/1454

Clarify why and where we stub out file set IDs
