sul-dlss/pre-assembly

- devel/prepare_content.rb
- lib/pre_assembly/reporting.rb
> checking for spaces in filename no longer necessary in discovery reports; generalizatons for rumsey prep script

- Gemfile
- Gemfile.lock
Not doing anything with them yet, but this is the direction we are moving in.
Related to #79, #85
> Introduce resque components

- .travis.yml
- README.md
- Rakefile
- bin/batch_run
- bin/correct_version
- bin/mods_report
- bin/mods_report2
- bin/remediate
- config/boot.rb
- integration/run_preassembly_spec.rb
- lib/pre_assembly/bundle.rb
- spec/spec_helper.rb
> Replaces ROBOT_ENVIRONMENT with RAILS_ENV vars, fixes #73

- config/deploy.rb
closes #82 this is only for stage, need to do prod now
> Disable honeybadger notification deploy

- .rubocop.yml
- spec/bundle_spec.rb
- spec/digital_object_spec.rb
- spec/druid_minter_spec.rb
- spec/object_file_spec.rb
- spec/remediate_spec.rb
- spec/smpl_project_specific_spec.rb
extends #107
These are the things that couldn't be auto-corrected.
> Start applying rubocop-rspec conventions.

- .rubocop.yml
- spec/bundle_spec.rb
- spec/digital_object_spec.rb
- spec/druid_minter_spec.rb
- spec/object_file_spec.rb
- spec/remediate_spec.rb
- spec/smpl_project_specific_spec.rb
> Rubocop rspec

- spec/bundle_spec.rb
- spec/druid_minter_spec.rb
- spec/smpl_project_specific_spec.rb
> More let statements, less spec instance vars

- lib/pre_assembly/bundle.rb
- lib/pre_assembly/reporting.rb
- spec/bundle_spec.rb
- spec/digital_object_spec.rb
- spec/druid_minter_spec.rb
- spec/remediate_spec.rb
- spec/smpl_project_specific_spec.rb
Extends #110, will rebase after that is merged.
Fixes #69
> Checksum bug

- .gitignore
- .rspec
- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
> Add rspec-rails

- app/lib/pre_assembly/digital_object.rb
- don't need to include all of the files in a way like that
> include PreAssembly::Project::Smpl

- spec/lib/pre_assembly/digital_object_spec.rb
Also no need to massage whitespace on nokogiri input.
> Replace last instance vars in digital_object_spec w/ let statements

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/migrate/20180904183131_create_users.rb
- db/schema.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
will need to add `has_one` or `has_many` relationship to `BundleContext` once it has been converted into an ActiveRecord model.
closes #171
closes #145
> User model

- app/services/discovery_report.rb
- spec/services/discover_report_spec.rb
> DiscoveryReport service: rename method, move smpl methods together

- app/jobs/discovery_report_job.rb
- spec/jobs/discovery_report_job_spec.rb
This is the super brain dead code from the generator;  hooking it up to actually do something is ticketed separately as #128
Closes #127
> DiscoveryReportJob class initial commit

- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- config/database.yml
- config/deploy.rb
- db/scripts/preassembly_setup.sql
- db/scripts/preassembly_test_setup.sql
also:
* add config/database.yml to linked_files in deploy config
* postgres setup instructions in local dev section of readme
> postgres initialization scripts for dev and test

- app/lib/pre_assembly/bundle.rb
- app/lib/pre_assembly/digital_object.rb
- app/models/bundle_context.rb
- config/settings.yml
- spec/lib/pre_assembly/digital_object_spec.rb
- spec/models/bundle_context_spec.rb
- spec/test_data/exemplar_templates/TEMPLATE.yaml
- spec/test_data/exemplar_templates/reg_example.yaml
- spec/test_data/project_config_files/flat_dir_images.yaml
- spec/test_data/project_config_files/folder_manifest.yaml
- spec/test_data/project_config_files/images_jp2_tif.yaml
- spec/test_data/project_config_files/local_dev_sohp.yaml
- spec/test_data/project_config_files/obj_dirs_images.yaml
- spec/test_data/project_config_files/proj_revs.yaml
- spec/test_data/project_config_files/proj_revs_bad_manifest.yaml
- spec/test_data/project_config_files/proj_revs_no_cm.yaml
- spec/test_data/project_config_files/smpl_multimedia.yaml
Closes #224
Also shared_configs PRs: sul-dlss/shared_configs#712, sul-dlss/shared_configs#713
> assembly_staging_dir (was staging_dir) comes from settings

- app/mailers/application_mailer.rb
- app/mailers/job_mailer.rb
- app/models/job_run.rb
- app/models/user.rb
- app/views/job_mailer/completion_email.text.erb
- spec/mailers/job_mailer_spec.rb
- spec/models/job_run_spec.rb
- spec/models/user_spec.rb
> Add job run mailer and hook up mailer to jobrun model

- app/lib/pre_assembly/bundle.rb
- app/lib/pre_assembly/digital_object.rb
- config/application.rb
- config/cli_environments/development.rb
- config/cli_environments/test.rb
- spec/lib/pre_assembly/bundle_spec.rb
D'oh!  I missed a few spots when I switched us to using settings.yml files in #269.  
Connects to #169  which will be done when I remove cli_environments from shared_configs
> Remove cli environments from app

- app/models/bundle_context.rb
- app/views/job_runs/show.html.erb
- spec/factories/bundle_contexts.rb
- spec/factories/job_runs.rb
- spec/mailers/job_mailer_spec.rb
- spec/models/bundle_context_spec.rb
- spec/models/job_run_spec.rb
- spec/support/bundle_setup.rb
- spec/views/bundle_context_spec.rb
- spec/views/job_runs/show.html.erb_spec.rb
> JobRun factory

- spec/factories/bundle_contexts.rb
- spec/mailers/job_mailer_spec.rb
- spec/models/bundle_context_spec.rb
- spec/models/job_run_spec.rb
- spec/support/bundle_setup.rb
- spec/views/bundle_context_spec.rb
For great cleanliness!
Also, let's **not** read the same YAML file 4 times just for one `bundle_context_from_hash`!
> BundleContext factory and conversion of specs to use it

- app/views/bundle_contexts/_yaml_form.erb
> Remove "YAML" from the description of the form

- Gemfile
- Gemfile.lock
- app/controllers/job_runs_controller.rb
- app/views/job_runs/index.html.erb
- app/views/job_runs/index.json.jbuilder
- app/views/job_runs/show.html.erb
- config/routes.rb
- spec/views/job_runs/index.html.erb_spec.rb
- spec/views/job_runs/index.json.jbuilder_spec.rb
> create index html and json views for job runs

- app/views/job_runs/show.html.erb
- spec/controllers/job_runs_controller_spec.rb
- spec/views/job_runs/show.html.erb_spec.rb
Displays view of Job Run with some Bundle Context data as well with corresponding rspec tests.
fixes #295
> Job run controller views

- config/deploy.rb
> Add deploy hooks for resque-pool

- app/controllers/job_runs_controller.rb
- app/views/job_runs/show.html.erb
- config/routes.rb
- spec/controllers/job_runs_controller_spec.rb
- spec/views/job_runs/show.html.erb_spec.rb
This covers both preassembly and discovery_report jobs. 
Fixes #259
> JobRunController download action

- db/schema.rb
- spec/controllers/bundle_contexts_controller_spec.rb
Do #373 first, please.
Part of #374
> BundleContexts unique index on user_id + project_name

- app/models/user.rb
- config/initializers/devise.rb
- db/migrate/20181001182157_change_column_name.rb
- db/schema.rb
- spec/controllers/bundle_contexts_controller_spec.rb
- spec/factories/users.rb
- spec/models/bundle_context_spec.rb
- spec/models/user_spec.rb
- spec/services/discovery_report_spec.rb
- spec/support/bundle_setup.rb
- i think the only place where this change will break things is the `output_dir`, but the BundleContext#output_dir is using `User.email` so it should be fine.
- changed the necessary RSpec tests to get this working / factories
> User email field from sunet id field

- app/models/user.rb
- config/initializers/devise.rb
- db/migrate/20181001182157_change_column_name.rb
- db/schema.rb
- spec/controllers/bundle_contexts_controller_spec.rb
- spec/factories/users.rb
- spec/models/bundle_context_spec.rb
- spec/models/user_spec.rb
- spec/services/discovery_report_spec.rb
- spec/support/bundle_setup.rb
going to add follow on PR that now changes all User.sunet_id to actual sunet_id's and not emails
> Undo user email

- app/views/bundle_contexts/_new_bc_form.erb
- app/views/bundle_contexts/new.html.erb
> Rename partial template: no more `yaml_form`

- spec/controllers/bundle_contexts_controller_spec.rb
- spec/factories/users.rb
- spec/models/bundle_context_spec.rb
- spec/models/user_spec.rb
- spec/services/discovery_report_spec.rb
- spec/support/bundle_setup.rb
> sunet_id without @stanford.edu

- app/models/bundle_context.rb
- config/initializers/bundle_dir_roots.yml.erb
- spec/controllers/bundle_contexts_controller_spec.rb
- spec/models/bundle_context_spec.rb
> Add beforesave and beforecreate call backs, for existence of bundle_dir

- app/lib/pre_assembly/bundle.rb
- app/models/bundle_context.rb
- spec/test_data/exemplar_templates/TEMPLATE.yaml
> remove defunct stageable_discovery config example

- README.md
probably good enough to say that this...
closes #260
> a few last touchups to wind down the webapp-ification of pre-assembly

- Gemfile
- Gemfile.lock
- lib/pre_assembly/digital_object.rb
- spec/digital_object_spec.rb
Fixes #430
This ports the work in https://github.com/sul-dlss/pre-assembly/pull/432 to the v3-legacy branch.
> Use dor-services-client to hit dor-services-app API

- README.md
> Clarify status of v3-legacy branch in README

- .rubocop_todo.yml
- Gemfile
- Gemfile.lock
- app/lib/pre_assembly/digital_object.rb
- spec/lib/pre_assembly/bundle_spec.rb
- spec/lib/pre_assembly/digital_object_spec.rb
Refs sul-dlss/dor-services-client#38
> Upgrade to dor-services-client 1.0.0

- config/boot.rb
> require workflow service in legacy branch

- app/views/job_runs/index.html.erb
> add link to resque from job runs page

- Gemfile.lock
> v3 legacy branch dep updates

- app/lib/pre_assembly/digital_object.rb
> Prune dead code

- app/lib/pre_assembly/digital_object.rb
> Remove unused code

- app/services/discovery_report.rb
- spec/services/discovery_report_spec.rb
Fixes a problem I introduced in e9a277fb25e9b3e5ba9690b70a3be7217888177d
Fixes #579
n/a
> Call the methods not the hash accessor

- app/lib/pre_assembly/bundle.rb
- spec/lib/pre_assembly/bundle_spec.rb
It is never used outside of tests
n/a
> Remove processed_pids

- Gemfile
- Gemfile.lock
Keep up to date with the rest of the infrastructure
n/a
> Upgrade dor-services-client

- app/lib/pre_assembly/digital_object.rb
- spec/lib/pre_assembly/digital_object_spec.rb
The version arg is `version:`, not `current_version:`.
> Invoke wf client with correct arg

- config/initializers/okcomputer.rb
To clarify the number of workers check in the comments
na
na
> okcomputer check gets a better comment

- app/controllers/bundle_contexts_controller.rb
- app/lib/pre_assembly/bundle.rb
- app/lib/pre_assembly/content_metadata_creator.rb
- app/lib/pre_assembly/digital_object.rb
- app/views/bundle_contexts/_new_bc_form.erb
- config/initializers/simple_form.rb
- config/initializers/simple_form_bootstrap.rb
- config/locales/en.yml
- db/migrate/20200317201845_add_public_to_bundle_context.rb
- db/schema.rb
- spec/factories/bundle_contexts.rb
- spec/lib/pre_assembly/bundle_spec.rb
- spec/lib/pre_assembly/content_metadata_creator_spec.rb
- spec/lib/pre_assembly/digital_object_spec.rb
This sets the preserve, shelve and publish to 'yes'
Fixes #625 
no
no
> Add an option to set all files public

- Gemfile
- Gemfile.lock
Compatibility with latest dor-services-app
Fixes #635 
n/a
yes.
> Update to dor-services-client 5

- app/lib/pre_assembly/batch.rb
meaningful names are easier to understand. no functional changes.
no
no
> Use meaningful names

- .rubocop.yml
- spec/controllers/batch_contexts_controller_spec.rb
- spec/controllers/job_runs_controller_spec.rb
- spec/jobs/discovery_report_job_spec.rb
- spec/jobs/preassembly_job_spec.rb
- spec/lib/csv_importer_spec.rb
- spec/lib/pre_assembly/batch_spec.rb
- spec/models/batch_context_spec.rb
- spec/models/job_run_spec.rb
- spec/models/user_spec.rb
- spec/services/discovery_report_spec.rb
- spec/views/bundle_context_spec.rb
- spec/views/shared/_header_spec.rb
> Add whitespace to improve readability

- Gemfile
- Gemfile.lock
Updates to dor-services-client 6.
No
No
> Updates to dor-services-client 6

- Gemfile
- Gemfile.lock
- app/models/batch_context.rb
- app/views/batch_contexts/_new_bc_form.erb
- spec/features/document_spec.rb
- spec/models/batch_context_spec.rb
- spec/test_data/pdf_document/content/document.pdf
- spec/test_data/pdf_document/manifest.csv
> Add a "document" content type

- README.md
- bin/prepare_content
Fixes #682
will be tested manually by Megan Trott or Andria Olsen
README.md, and https://consul.stanford.edu/pages/viewpage.action?pageId=146704638
> Add the prepare_content script from lyberservices-scripts

- Gemfile.lock
required for recent changes for items being in multiple collections
> Update the dor-services-client for compatibility with DSA

- Gemfile
- Gemfile.lock
> Updated dor-services-client to 6.17.0

- Gemfile
- Gemfile.lock
> Update cocina-models to 0.55.0

- Gemfile.lock
Use the latest models and gems.
CI
None
> Bump cocina-models and related gems

- Gemfile
- Gemfile.lock
> Update to dor-services-app 7 (cocina-models 0.61.0)

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- README.md
> orbify circle config; add codeclimate badge to readme

- README.md
Also, test out codeclimate in the build again.
> Add a colon for enhanced readability

- app/lib/pre_assembly/batch.rb
- app/services/discovery_report.rb
- app/views/job_runs/index.html.erb
- spec/lib/pre_assembly/batch_spec.rb
Fix timestamp in logs; show times to user in Pacific instead of UTC
> Fix timestamps

- .rubocop.yml
- app/lib/pre_assembly/batch.rb
- config/initializers/devise.rb
She who adds rubocops saves the world entire.
> add new rubocops

- Gemfile
- Gemfile.lock
We were not ever using the code provided in this gem
test suite
> Remove resque-lock from the bundle

- README.md
Avoiding carpal tunnel. 
locally
> Use bin/rails as it is less typing than bundle exec rails

- app/assets/javascripts/job_runs.js
- app/assets/stylesheets/job_runs.css
Extra files are just clutter.
locally.
> Remove empty files

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/views/layouts/application.html.erb
propshaft is the modern rails asset pipeline
tested locally
> Switch to propshaft as the asset pipeline

- app/assets/stylesheets/application.css
- app/views/batch_contexts/_batch_context.html.erb
- app/views/batch_contexts/_new_bc_form.erb
- app/views/batch_contexts/new.html.erb
- app/views/job_runs/show.html.erb
- app/views/layouts/application.html.erb
> Updated to Bootstrap 5.

- app/assets/stylesheets/application.css
- app/views/shared/_header.html.erb
So that we can control the color in one place. 
Locally
> Use the css custom property for the brand color

- app/models/batch_context.rb
- app/models/job_run.rb
Follow on from #981 - some more code comments explaining what the classes are, since it's not obvious
> some more code comments about job_runs and batch_contexts

- app/lib/pre_assembly/batch.rb
- app/services/discovery_report.rb
- spec/lib/pre_assembly/batch_spec.rb
- spec/services/discovery_report_spec.rb
- spec/services/object_file_validator_spec.rb
> refactor batch.rb for improved maintainability

- app/lib/pre_assembly/batch.rb
> batch.rb: improve some method comments

- app/lib/pre_assembly/assembly_directory.rb
- app/lib/pre_assembly/digital_object.rb
- bin/prepare_content
- spec/lib/pre_assembly/assembly_directory_spec.rb
- spec/lib/pre_assembly/digital_object_spec.rb
for better code maintainability
> assembly_directory.rb: make methods private and improve comments

- app/lib/pre_assembly/batch.rb
for better maintainability of code.
> batch.rb: improve some variable names

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- config/database.yml
- db/schema.rb
- docker-compose.yml
- spec/views/bundle_contexts/show.html.erb_spec.rb
To avoid database contention issues
CI
> Run tests on a real RDBMS

- app/lib/pre_assembly/batch.rb
- app/services/discovery_report.rb
- spec/lib/pre_assembly/batch_spec.rb
- spec/services/discovery_report_spec.rb
a bit of code cleanup following https://github.com/sul-dlss/pre-assembly/pull/965 (including suggestions made by @mjgiarlo in PR review)
unit tests
> Various touchups

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
So everything works with ubuntu migration
> tweaks for ubuntu migration

- bin/prepare_content
This variable is never accessed.
> Remove unused variable

- app/jobs/discovery_report_job.rb
> Pretty print the JSON output of the discovery report

- app/assets/stylesheets/application.css
- app/views/job_runs/show.html.erb
Closes #1027 
@andrewjbtw do you want to test this somewhere first, or is it a simple enough change to not worry about?
N/A
> Shift view summary link on discovery report

- app/lib/pre_assembly/from_staging_location/file_set.rb
> Fix typo in constant

- spec/support/batch_setup.rb
> Remove unused method

- app/lib/pre_assembly/batch.rb
- app/lib/pre_assembly/digital_object.rb
- app/lib/pre_assembly/file_manifest.rb
- app/models/batch_context.rb
- app/services/object_file_validator.rb
- spec/lib/pre_assembly/file_manifest_spec.rb
- spec/support/batch_setup.rb
This will help support a second kind of manifest file.
Ref #952
CI
> [refactor] Pass the file_manifest into the batch

- .circleci/config.yml
> Bump sul-dlss orb to 3.1.2

- app/lib/pre_assembly/batch.rb
- app/models/batch_context.rb
- spec/lib/pre_assembly/batch_spec.rb
- spec/models/batch_context_spec.rb
This helps keep it conceptually separate from the file_manifest
CI
> Rename manifest to object_mainfest

- spec/services/start_accession_spec.rb
> Rename test let block to match the attribute

- app/lib/pre_assembly/batch.rb
- app/lib/pre_assembly/digital_object.rb
- app/services/discovery_report.rb
- spec/lib/pre_assembly/digital_object_spec.rb
- spec/lib/pre_assembly/file_manifest_spec.rb
- spec/services/discovery_report_spec.rb
- spec/services/object_file_validator_spec.rb
- spec/spec_helper.rb
Pid could vary depending on what was passed in (either namespaced or not), but the druid property is normalized, so it is always consistent
CI
> Expose druid rather than pid

- spec/lib/pre_assembly/digital_object_spec.rb
We don't need 5 copies of this code.
> Move a common stub up into a shared context

- spec/lib/pre_assembly/digital_object_spec.rb
- spec/lib/pre_assembly/file_manifest_spec.rb
These make it more challenging to understand the test
CI
> Remove unnecessary stubs

- spec/lib/pre_assembly/file_manifest_spec.rb
Removes unnecessary complexity
> Remove more unnecessary stubs

- app/lib/pre_assembly/file_manifest.rb
Reduce complexity of this method.
> [refactor] Extract a method for building file properties

- Gemfile
- Gemfile.lock
Pick up bug fixes in the most recent version of the assembly-objectfile gem.
CI
> Update assembly-objectfile to 2.x

- app/lib/pre_assembly/assembly_directory.rb
This is safer than just deleting the code and seeing what breaks.
CI
> Add a honeybadger notification on a potentially dead code path

- bin/prepare_content
So we know how recently this is used.
n/a
> Update date prepare_content was last seen in use

- Gemfile.lock
This fixes a bug around exif handling of files without exif data
> Update assembly-objectfile to 2.1.2

- app/views/layouts/application.html.erb
Skypack is having trouble.
Fixes #1092
locally
> Switch CDNs for Turbo

- app/views/layouts/application.html.erb
Keep dependencies up to date.
locally
> Upgrade bootstrap to 5.2.1

- .rubocop.yml
- app/controllers/job_runs_controller.rb
- config/initializers/load_config.rb
She who adds cops and fixes saves the world entire.
> add new rubocops and concomittant tweaks to code

- app/lib/pre_assembly/from_staging_location/file.rb
removing cruft.
specs.  I also "ack"ed and it's never used.
> remove provider_sha1 as it is never used

- app/lib/pre_assembly/assembly_directory.rb
It's been around for nearly a year and this code has never been tripped in any env during that time. That suggests this is in fact dead code, which the Honeybadger experiment was put in place to test. Declare the experiment a success and clean up.
CI
> Remove honeybadger experiment

- .rubocop.yml
- spec/factories/job_runs.rb
- spec/services/discovery_report_spec.rb
> add new rubocops and tweaks

- Gemfile
- Gemfile.lock
- app/lib/pre_assembly/digital_object.rb
- config/settings.yml
- spec/features/preassembly_run/book_using_file_manifest_spec.rb
- spec/features/preassembly_run/dark_file_object_spec.rb
- spec/features/preassembly_run/document_spec.rb
- spec/features/preassembly_run/hierarchial_files_with_manifest_spec.rb
- spec/features/preassembly_run/hierarchical_files_spec.rb
- spec/features/preassembly_run/image_spec.rb
- spec/features/preassembly_run/media_audio_spec.rb
- spec/features/preassembly_run/media_video_spec.rb
- spec/features/preassembly_run/no_files_spec.rb
- spec/features/preassembly_run/public_tif_spec.rb
- spec/lib/pre_assembly/batch_spec.rb
- spec/lib/pre_assembly/digital_object_spec.rb
Fixes #1171
When an item is already in accessioning, do not proceed with pre-assembly.
> Check if item is already accessioning when pre-assembling

- .rubocop.yml
- spec/features/discovery_report/build_manifest_image_spec.rb
- spec/features/discovery_report/file_manifest_book_spec.rb
- spec/features/discovery_report/hierarchical_files_spec.rb
- spec/jobs/discovery_report_job_spec.rb
- spec/jobs/preassembly_job_spec.rb
- spec/lib/pre_assembly/digital_object_spec.rb
- spec/support/batch_setup.rb
Enable new cops and autocorrect errors.
> Enable new cops and fix linting errors

- README.md
To provide some details about the internal data model for developers who aren't already familiar with pre-assembly.
n/a
No
> Added some notes about the data model

- spec/lib/pre_assembly/file_manifest_spec.rb
> Refactor file manifest spec.

- Gemfile
To reduce future cognitive load
CI
nope
> Gemfile - keep gems together instead of scattered

- app/lib/pre_assembly/digital_object.rb
- app/services/discovery_report.rb
- app/services/structural_files_differ.rb
- spec/features/discovery_report/build_manifest_image_spec.rb
- spec/features/discovery_report/completed_with_errors_spec.rb
- spec/features/discovery_report/file_manifest_book_spec.rb
- spec/features/discovery_report/hierarchical_files_spec.rb
- spec/services/discovery_report_spec.rb
- spec/services/structural_files_differ_spec.rb
closes #1195
Show the user what is changing before initiating accessioning.
Unit
> Adds support for diffing structural files.

- app/views/batch_contexts/_batch_context.html.erb
- spec/views/bundle_contexts/show.html.erb_spec.rb
closes #1231
Per ticket
Unit, QA
> Adds job run table to batch context detail page.

- Gemfile
- Gemfile.lock
- config/initializers/okcomputer.rb
- config/initializers/sneakers.rb
- config/settings.yml
- lib/tasks/rabbit.rake
closes #1199
Prep work for preassembly to be notified when a deposit is complete.
QA
> Adds rabbit and sneaker configuration.

- app/views/batch_contexts/_actions.html.erb
- app/views/batch_contexts/_batch_context.html.erb
- app/views/job_runs/show.html.erb
Follow on from #1237; we had a partial that has the buttons already and it can be used.  Also, move the shared partial so it's associated with the batch context and refactor a bit.
Localhost and CI
> reuse an existing partial for action buttons

- app/jobs/preassembly_job.rb
- app/lib/pre_assembly/batch.rb
- app/lib/pre_assembly/digital_object.rb
- app/models/accession.rb
- app/models/batch_context.rb
- app/models/job_run.rb
- db/migrate/20230905160434_create_accessions.rb
- db/schema.rb
- spec/jobs/preassembly_job_spec.rb
- spec/lib/pre_assembly/batch_spec.rb
- spec/lib/pre_assembly/digital_object_spec.rb
- spec/models/batch_context_spec.rb
- spec/models/job_run_spec.rb
- spec/services/discovery_report_spec.rb
- spec/support/batch_setup.rb
closes #1219
Unit, Integration
> Adds accession model.

- README.md
For tests to pass in local development you should make sure to install
Javascript dependencies and build the CSS.
n/a
n/a
> Document some extra setup

- app/assets/stylesheets/main.scss
- app/controllers/job_runs_controller.rb
- app/views/job_runs/_discovery_report_summary.html.erb
- app/views/job_runs/_structural_updates_summary.html.erb
> Add structure file changes to the discovery report display

- Rakefile
- app/jobs/accession_complete_job.rb
- app/jobs/job_run_complete_job.rb
- app/models/accession.rb
- config/deploy.rb
- db/migrate/20230908185452_add_state_to_accession.rb
- db/schema.rb
- lib/tasks/rabbit.rake
- spec/factories/accessions.rb
- spec/jobs/accession_complete_job_spec.rb
> Update accessions from rabbit messages.

- spec/jobs/accession_complete_job_spec.rb
> Add sneakers to deploy.

- app/views/batch_contexts/index.html.erb
- app/views/batch_contexts/new.html.erb
- app/views/batch_contexts/show.html.erb
- app/views/job_runs/discovery_report_summary.html.erb
- app/views/job_runs/index.html.erb
- app/views/job_runs/progress_log.html.erb
- app/views/job_runs/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_header.html.erb
Fixes #1260 to provide a skip-nav link.
Deployed to QA and works with VoiceOver and keyboard (at least in Chrome) correctly. Is invisible initially and then upon tab becomes visible (below):
No new ones
> Add skip link

- app/views/layouts/application.html.erb
Fixes #1258.
Confirmed with Axe DevTools that violation is no longer noted. 
None further.
> Add lang attribute

- app/jobs/discovery_report_job.rb
- app/jobs/preassembly_job.rb
- app/models/job_run.rb
- spec/models/job_run_spec.rb
- spec/views/job_runs/show.html.erb_spec.rb
closes #1251
To avoid bad states.
Unit
> Change approach to preassembly/discovery transition.

- app/lib/pre_assembly/file_manifest.rb
- spec/fixtures/media_missing/file_manifest_blank_rows.csv
- spec/fixtures/media_missing/file_manifest_missing_druid_column.csv
- spec/lib/pre_assembly/file_manifest_spec.rb
Fixes #1280 - ignore blank lines in file manifest
Updated tests
> ignore blank lines in file manifest

- README.md
- app/models/batch_context.rb
- app/models/globus_destination.rb
- app/models/user.rb
- db/migrate/20230920123240_create_globus_destinations.rb
- db/schema.rb
Refs #1188, to add a GlobusDestination model and a GlobusDestinations table to db.
Unit
> Add GlobusDestination model

- app/lib/pre_assembly/file_identifier_generator.rb
- app/lib/pre_assembly/file_manifest.rb
- app/lib/pre_assembly/from_staging_location/structural_builder.rb
- spec/lib/pre_assembly/digital_object_spec.rb
- spec/lib/pre_assembly/file_manifest_spec.rb
> Makes testing of file identifier generation deterministic.

- config/settings.yml
> Add globus client settings

- Gemfile
- Gemfile.lock
- README.md
- config/initializers/globus_client.rb
Refs #1188 to set up GlobusClient. 
Unit. Also successfully did a client operation from rails console locally.
> Initial GlobusClient configuration

- app/assets/stylesheets/main.scss
- app/views/shared/_header.html.erb
Fixes #1255 
Confirmed with AXE DevTools that the alt text is correctly found. 
Not any further.
> SUL image alt text

- app/mailers/job_mailer.rb
- app/models/job_run.rb
- app/views/job_mailer/completion_email.text.erb
- config/settings.yml
- spec/mailers/job_mailer_spec.rb
- spec/models/job_run_spec.rb
Closes #1220 
Note: this has been rebased on main after https://github.com/sul-dlss/pre-assembly/pull/1281/
Unit
no
> Update the notification email for completed accessioning

- app/jobs/accession_complete_job.rb
- app/mailers/job_mailer.rb
- app/models/job_run.rb
- app/views/job_mailer/accession_completion_email.text.erb
- app/views/job_mailer/completion_email.text.erb
- spec/mailers/job_mailer_spec.rb
- spec/models/job_run_spec.rb
- spec/spec_helper.rb
closes #1220
Unit, integration, Andrew
> Fix / refactor accessioning complete emails.

- app/jobs/accession_complete_job.rb
So that accessions are correctly marked as completed.
QA
> Do not use instance variables in AccessionCompleteJob.

- app/views/job_runs/_details.html.erb
- app/views/job_runs/show.html.erb
- spec/views/job_runs/show.html.erb_spec.rb
Closes #1324 
Before:
After (header updated, sunet in details):
> Reformat the job page header for clarity

- .rubocop.yml
- app/models/job_run.rb
- config/locales/en.yml
- spec/features/discovery_report/completed_with_errors_spec.rb
- spec/features/preassembly_run/no_files_spec.rb
- spec/jobs/job_run_complete_job_spec.rb
- spec/models/job_run_spec.rb
closes #1316
See ticket
Unit, Andrew
> Change Job Run human state names

- app/lib/pre_assembly/digital_object.rb
- app/services/discovery_report.rb
- spec/features/discovery_report/build_manifest_image_spec.rb
- spec/features/discovery_report/completed_with_errors_spec.rb
- spec/features/discovery_report/file_manifest_book_spec.rb
- spec/features/discovery_report/hierarchical_files_spec.rb
- spec/services/discovery_report_spec.rb
> Omit file diff report for first versions of items.

- .rubocop.yml
- app/controllers/job_runs_controller.rb
- app/views/job_runs/process_log.html.erb
- app/views/job_runs/show.html.erb
- config/routes.rb
- spec/rails_helper.rb
- spec/requests/job_run_process_log_spec.rb
- spec/support/devise.rb
closes #1202
Per ticket
Unit, Andrew
> Adds process log to job run page.

- app/views/job_runs/show.html.erb
Fixes #1366 - align buttons with return link (see screenshot below for how it looks with the change)
Localhost
> better align action buttons with return link

- app/views/layouts/application.html.erb
- config/settings.yml
> Adds google analytics

- config/initializers/okcomputer.rb
Because if these queues are not setup correctly, it can cause weird unexpected behavior.
Can be fixed with a `RAILS_ENV=production bin/rake rabbitmq:setup` on the server, but at least this alerts us to the problem.
Deployed to stage.
> add okcomputer check for rabbitmq queue existence

- config/initializers/okcomputer.rb
Reduce number of rabbit connections from OK Computer.
QA
> Refinement to rabbitmq OK computer check.

- Gemfile
- Gemfile.lock
> Update cocina models and DSC

- app/views/layouts/application.html.erb
Previously we had different versions for the Bootstrap JS and the CSS
> Update bootstrap to 5.3.3

- app/services/start_accession.rb
- spec/services/start_accession_spec.rb
> Remove significance from start accession service

- app/lib/pre_assembly/digital_object.rb
- spec/features/preassembly_run/book_using_file_manifest_spec.rb
- spec/features/preassembly_run/dark_file_object_spec.rb
- spec/features/preassembly_run/document_spec.rb
- spec/features/preassembly_run/geo_spec.rb
- spec/features/preassembly_run/hierarchial_files_with_manifest_spec.rb
- spec/features/preassembly_run/hierarchical_files_spec.rb
- spec/features/preassembly_run/image_spec.rb
- spec/features/preassembly_run/media_audio_spec.rb
- spec/features/preassembly_run/media_video_spec.rb
- spec/features/preassembly_run/no_files_spec.rb
- spec/features/preassembly_run/public_tif_spec.rb
- spec/lib/pre_assembly/batch_spec.rb
- spec/lib/pre_assembly/digital_object_spec.rb
Ref https://github.com/sul-dlss/dor-services-app/issues/4864
https://argo-qa.stanford.edu/view/tg624bc8823
Tested via `SDR_ENV=qa ber spec/features/preassembly_reaccessioning_spec.rb`
> Open a version if it's not open already

- config/resque.yml
> Remove unused Resque config

- Gemfile.lock
- app/controllers/batch_contexts_controller.rb
- app/helpers/application_helper.rb
- app/javascript/controllers/ocr_controller.js
- app/lib/pre_assembly/digital_object.rb
- app/models/batch_context.rb
- app/services/start_accession.rb
- app/views/batch_contexts/_new_bc_form.erb
- config/settings.yml
- db/migrate/20240510155525_ocr.rb
- db/schema.rb
- spec/features/preassembly_run/book_using_file_manifest_spec.rb
- spec/features/preassembly_run/dark_file_object_spec.rb
- spec/features/preassembly_run/document_spec.rb
- spec/features/preassembly_run/geo_spec.rb
- spec/features/preassembly_run/hierarchial_files_with_manifest_spec.rb
- spec/features/preassembly_run/hierarchical_files_spec.rb
- spec/features/preassembly_run/image_spec.rb
- spec/features/preassembly_run/media_audio_spec.rb
- spec/features/preassembly_run/media_video_spec.rb
- spec/features/preassembly_run/no_files_spec.rb
- spec/features/preassembly_run/public_tif_spec.rb
- spec/services/start_accession_spec.rb
Fixes https://github.com/sul-dlss/pre-assembly/issues/1430 - add initial drop downs for pre-assembly UI
~~HOLD for PO review~~
~~Note: this will not work until we get https://github.com/sul-dlss/dor-services-app/pull/4983 and https://github.com/sul-dlss/dor-services-client/pull/428 and the update to the latest dor-services-client here~~
Issues:
- Missing language selection; will add in separate ticket: #1439
Localhost
> add ocr selections

- app/assets/stylesheets/main.scss
- app/views/batch_contexts/_new_bc_form.erb
- app/views/job_runs/recent_history.html.erb
- spec/features/discovery_report/build_manifest_image_spec.rb
- spec/features/discovery_report/completed_with_errors_spec.rb
- spec/features/discovery_report/discovery_report_failed_spec.rb
- spec/features/discovery_report/file_manifest_book_spec.rb
- spec/features/discovery_report/hierarchical_files_spec.rb
- spec/features/preassembly_run/book_using_file_manifest_spec.rb
- spec/features/preassembly_run/dark_file_object_spec.rb
- spec/features/preassembly_run/document_spec.rb
- spec/features/preassembly_run/geo_spec.rb
- spec/features/preassembly_run/hierarchial_files_with_manifest_spec.rb
- spec/features/preassembly_run/hierarchical_files_spec.rb
- spec/features/preassembly_run/image_spec.rb
- spec/features/preassembly_run/media_audio_spec.rb
- spec/features/preassembly_run/media_video_spec.rb
- spec/features/preassembly_run/no_files_spec.rb
- spec/features/preassembly_run/preassembly_failed_spec.rb
- spec/features/preassembly_run/public_tif_spec.rb
- Fixes for skipped headers and contrast errors
browser
> accesibility updates based on WAVE extension

- app/lib/pre_assembly/digital_object.rb
> Update version description

- app/javascript/controllers/ocr_controller.js
- app/views/batch_contexts/_new_bc_form.erb
> update language headers

- app/lib/pre_assembly/from_staging_location/file.rb
closes #1461
Shelving without publishing doesn't work.
> Change png to not shelve.

- app/lib/pre_assembly/from_staging_location/file.rb
> change jp2 settings

- app/javascript/controllers/ocr_controller.js
Fixes #1471 - refine text of OCR questions in pre-assembly form
Localhost
> text changes to OCR labels

- Gemfile
- Gemfile.lock
- app/views/batch_contexts/index.html.erb
- app/views/batch_contexts/new.html.erb
- app/views/job_runs/index.html.erb
- app/views/layouts/mailer.html.erb
- public/404.html
- public/422.html
- public/500.html
- spec/features/axe_spec.rb
- spec/features/discovery_report/completed_with_errors_spec.rb
> add axe testing to rspec and fix accessiblity issues

- app/assets/stylesheets/main.scss
- app/assets/stylesheets/palette.scss
- app/javascript/controllers/ocr_controller.js
- app/views/batch_contexts/_new_bc_form.erb
> update styling on form

- app/views/batch_contexts/_jobs_summary.html.erb
Fix accessibility heading skipping
> accessibility heading fix

- app/views/batch_contexts/_details.html.erb
- app/views/batch_contexts/_settings.html.erb
- app/views/batch_contexts/index.html.erb
- app/views/batch_contexts/new.html.erb
- app/views/job_runs/_details.html.erb
- app/views/job_runs/index.html.erb
- app/views/job_runs/recent_history.html.erb
> update table styling

- app/views/batch_contexts/_details.html.erb
- app/views/batch_contexts/_new_bc_form.erb
- app/views/batch_contexts/_settings.html.erb
- app/views/batch_contexts/show.html.erb
- app/views/job_runs/_details.html.erb
- app/views/job_runs/recent_history.html.erb
- app/views/job_runs/show.html.erb
Requested styling updates from Andrew and Alan.
> small styling updates

- app/views/batch_contexts/new.html.erb
Requested by Alan to prevent table wrapping
> change form column size

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/lib/csv_importer.rb
- app/models/globus_destination.rb
- lib/tasks/reports.rake
Keep pace with Ruby upgrades
CI
> Bump Ruby to 3.3.1

- app/views/batch_contexts/_alert.html.erb
> update alert styling to match component library

- app/assets/stylesheets/main.scss
- app/views/batch_contexts/index.html.erb
> add break-all to name + staging location

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
Small tech-debt PR to pull in debug as we have in other apps.
> Switch from byebug to debug to match other apps

- README.md
Realized the README needed a quick update after removing byebug.
> Update README for updated debugger

- app/views/batch_contexts/_alert.html.erb
Fixes #1546 - update warning message
Localhost
> updated warning message

- .circleci/config.yml
- .rubocop.yml
- Gemfile.lock
Ruby 3.4.1 upgrade patch party
> update to ruby 3.4.1

- .circleci/config.yml
- .codecov.yml
> Remove per-project config (use global config for org)

- Gemfile
- Gemfile.lock
- app/lib/pre_assembly/digital_object.rb
- config/settings.yml
- spec/features/discovery_report/build_manifest_image_spec.rb
- spec/features/discovery_report/completed_with_errors_spec.rb
- spec/features/discovery_report/file_manifest_book_spec.rb
- spec/features/discovery_report/hierarchical_files_spec.rb
- spec/features/preassembly_run/book_using_file_manifest_spec.rb
- spec/features/preassembly_run/dark_file_object_spec.rb
- spec/features/preassembly_run/document_spec.rb
- spec/features/preassembly_run/geo_spec.rb
- spec/features/preassembly_run/hierarchical_files_spec.rb
- spec/features/preassembly_run/hierarchical_files_with_manifest_spec.rb
- spec/features/preassembly_run/image_spec.rb
- spec/features/preassembly_run/media_audio_spec.rb
- spec/features/preassembly_run/media_video_spec.rb
- spec/features/preassembly_run/no_files_spec.rb
- spec/features/preassembly_run/public_tif_spec.rb
- spec/lib/pre_assembly/digital_object_spec.rb
- spec/services/discovery_report_spec.rb
To remove workflow client, which isn't necessary.
Unit, stage integration tests
> Remove workflow client.

- app/views/batch_contexts/_alert.html.erb
Small text change, see https://github.com/sul-dlss/pre-assembly/issues/1604#issuecomment-3114372545
Localhost
> another text change

- app/views/batch_contexts/_alert.html.erb
> add missing sentence
